# Generated by Django 5.2.17 on 2026-09-23 21:40

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipamentoTI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("notebook", "Notebook"),
                            ("desktop", "Desktop"),
                            ("servidor", "Servidor"),
                            ("switch", "Switch"),
                            ("roteador", "Roteador"),
                            ("impressora", "Impressora"),
                            ("monitor", "Monitor"),
                            ("outro", "Outro"),
                        ],
                        default="notebook",
                        max_length=20,
                    ),
                ),
                ("usuario", models.CharField(blank=True, max_length=200)),
                ("setor", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("manutencao", "Em manutenção"),
                            ("disponivel", "Disponível"),
                            ("descarte", "Descarte"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("ultima_revisao", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["codigo"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="helpdesk_eq_tenant__460ff2_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "tipo"], name="helpdesk_eq_tenant__b1b987_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "codigo"), name="uniq_equipamento_codigo_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEquipamentoTI",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("notebook", "Notebook"),
                            ("desktop", "Desktop"),
                            ("servidor", "Servidor"),
                            ("switch", "Switch"),
                            ("roteador", "Roteador"),
                            ("impressora", "Impressora"),
                            ("monitor", "Monitor"),
                            ("outro", "Outro"),
                        ],
                        default="notebook",
                        max_length=20,
                    ),
                ),
                ("usuario", models.CharField(blank=True, max_length=200)),
                ("setor", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("manutencao", "Em manutenção"),
                            ("disponivel", "Disponível"),
                            ("descarte", "Descarte"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("ultima_revisao", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical equipamento ti",
                "verbose_name_plural": "historical equipamento tis",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalTicket",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("solicitante", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("rede", "Rede"),
                            ("acesso", "Acesso"),
                            ("mobile", "Mobile"),
                            ("infraestrutura", "Infraestrutura"),
                            ("equipamento", "Equipamento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_atendimento", "Em atendimento"),
                            ("aguardando", "Aguardando"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("sla_horas", models.IntegerField(default=24)),
                ("atendente", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolvido_em", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ticket",
                "verbose_name_plural": "historical tickets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("solicitante", models.CharField(max_length=200)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("hardware", "Hardware"),
                            ("software", "Software"),
                            ("rede", "Rede"),
                            ("acesso", "Acesso"),
                            ("mobile", "Mobile"),
                            ("infraestrutura", "Infraestrutura"),
                            ("equipamento", "Equipamento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_atendimento", "Em atendimento"),
                            ("aguardando", "Aguardando"),
                            ("resolvido", "Resolvido"),
                            ("fechado", "Fechado"),
                        ],
                        default="aberto",
                        max_length=20,
                    ),
                ),
                ("sla_horas", models.IntegerField(default=24)),
                ("atendente", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolvido_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="helpdesk_ti_tenant__7aa3af_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "prioridade"], name="helpdesk_ti_tenant__73d188_idx"
                    ),
                ],
            },
        ),
    ]
