# Generated by Django 5.2.17 on 2026-09-26 18:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0015_conectores_segredos_sync"),
        ("helpdesk", "0002_equipamentoti_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalticket",
            name="agente",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agency.agent",
            ),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="incidente_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="origem",
            field=models.CharField(
                choices=[
                    ("manual", "Aberto por pessoa"),
                    ("incidente", "Incidente (monitoramento)"),
                    ("agente", "Aberto por agente"),
                    ("email", "E-mail"),
                ],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="prazo_sla",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="primeira_resposta_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="solucao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalticket",
            name="task",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agency.task",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="agente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados",
                to="agency.agent",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="incidente_id",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="origem",
            field=models.CharField(
                choices=[
                    ("manual", "Aberto por pessoa"),
                    ("incidente", "Incidente (monitoramento)"),
                    ("agente", "Aberto por agente"),
                    ("email", "E-mail"),
                ],
                default="manual",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="prazo_sla",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="primeira_resposta_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="solucao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chamados",
                to="agency.task",
            ),
        ),
        migrations.AlterField(
            model_name="historicalticket",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("rede", "Rede"),
                    ("acesso", "Acesso"),
                    ("mobile", "Mobile"),
                    ("infraestrutura", "Infraestrutura"),
                    ("equipamento", "Equipamento"),
                    ("sistema", "Sistema (PGBA)"),
                    ("banco", "Banco de dados"),
                    ("integracao", "Integração / API / MCP"),
                    ("ia", "IA / agentes"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("hardware", "Hardware"),
                    ("software", "Software"),
                    ("rede", "Rede"),
                    ("acesso", "Acesso"),
                    ("mobile", "Mobile"),
                    ("infraestrutura", "Infraestrutura"),
                    ("equipamento", "Equipamento"),
                    ("sistema", "Sistema (PGBA)"),
                    ("banco", "Banco de dados"),
                    ("integracao", "Integração / API / MCP"),
                    ("ia", "IA / agentes"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="InteracaoChamado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("comentario", "Comentário"),
                            ("resposta", "Resposta ao solicitante"),
                            ("ia", "Sugestão da IA"),
                            ("sistema", "Sistema"),
                        ],
                        default="comentario",
                        max_length=12,
                    ),
                ),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("texto", models.TextField()),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interacoes",
                        to="helpdesk.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "ticket"], name="helpdesk_in_tenant__fc6ac3_idx"
                    )
                ],
            },
        ),
    ]
