# Generated by Django 5.2.17 on 2026-09-23 21:40

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["tenant_id"], name="erp_fornece_tenant__855718_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Funcionario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=100)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("salario", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("data_admissao", models.DateField()),
                ("data_demissao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("ferias", "Férias"),
                            ("afastado", "Afastado"),
                            ("desligado", "Desligado"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="erp_funcion_tenant__d16128_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "departamento"], name="erp_funcion_tenant__98e836_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFornecedor",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefone", models.CharField(blank=True, max_length=30)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical fornecedor",
                "verbose_name_plural": "historical fornecedors",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFuncionario",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("cargo", models.CharField(max_length=100)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("salario", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("data_admissao", models.DateField()),
                ("data_demissao", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("ferias", "Férias"),
                            ("afastado", "Afastado"),
                            ("desligado", "Desligado"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("cpf", models.CharField(blank=True, max_length=14)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical funcionario",
                "verbose_name_plural": "historical funcionarios",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItemEstoque",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=200)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("quantidade", models.IntegerField(default=0)),
                ("quantidade_minima", models.IntegerField(default=0)),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("un", "Unidade"),
                            ("kg", "Kg"),
                            ("m", "Metro"),
                            ("l", "Litro"),
                            ("cx", "Caixa"),
                            ("pc", "Peça"),
                        ],
                        default="un",
                        max_length=5,
                    ),
                ),
                ("custo_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("localizacao", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="erp.fornecedor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item estoque",
                "verbose_name_plural": "historical item estoques",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")], max_length=10
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("operacional", "Operacional"),
                            ("pessoal", "Pessoal"),
                            ("impostos", "Impostos"),
                            ("servicos", "Serviços"),
                            ("vendas", "Vendas"),
                            ("investimento", "Investimento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=15,
                    ),
                ),
                ("cliente", models.CharField(blank=True, max_length=200)),
                ("fornecedor_nome", models.CharField(blank=True, max_length=200)),
                ("numero_documento", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical lancamento financeiro",
                "verbose_name_plural": "historical lancamento financeiros",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrdemCompra",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("aprovado", "Aprovado"),
                            ("enviado", "Enviado ao fornecedor"),
                            ("recebido", "Recebido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=15,
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("data_emissao", models.DateField(default=django.utils.timezone.now)),
                ("data_entrega_prevista", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="erp.fornecedor",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical ordem compra",
                "verbose_name_plural": "historical ordem compras",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")], max_length=10
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("vencimento", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("pago", "Pago"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendente",
                        max_length=10,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("operacional", "Operacional"),
                            ("pessoal", "Pessoal"),
                            ("impostos", "Impostos"),
                            ("servicos", "Serviços"),
                            ("vendas", "Vendas"),
                            ("investimento", "Investimento"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=15,
                    ),
                ),
                ("cliente", models.CharField(blank=True, max_length=200)),
                ("fornecedor_nome", models.CharField(blank=True, max_length=200)),
                ("numero_documento", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["vencimento"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "tipo", "status"],
                        name="erp_lancame_tenant__c296c0_idx",
                    ),
                    models.Index(
                        fields=["tenant_id", "vencimento"], name="erp_lancame_tenant__13bf67_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ItemEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("codigo", models.CharField(max_length=50)),
                ("nome", models.CharField(max_length=200)),
                ("categoria", models.CharField(blank=True, max_length=100)),
                ("quantidade", models.IntegerField(default=0)),
                ("quantidade_minima", models.IntegerField(default=0)),
                (
                    "unidade",
                    models.CharField(
                        choices=[
                            ("un", "Unidade"),
                            ("kg", "Kg"),
                            ("m", "Metro"),
                            ("l", "Litro"),
                            ("cx", "Caixa"),
                            ("pc", "Peça"),
                        ],
                        default="un",
                        max_length=5,
                    ),
                ),
                ("custo_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("localizacao", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="itens_estoque",
                        to="erp.fornecedor",
                    ),
                ),
            ],
            options={
                "ordering": ["nome"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "categoria"], name="erp_itemest_tenant__d7ac0e_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "codigo"], name="erp_itemest_tenant__fd96b2_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "codigo"), name="uniq_item_estoque_codigo_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrdemCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("aprovado", "Aprovado"),
                            ("enviado", "Enviado ao fornecedor"),
                            ("recebido", "Recebido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=15,
                    ),
                ),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("data_emissao", models.DateField(default=django.utils.timezone.now)),
                ("data_entrega_prevista", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordens_compra",
                        to="erp.fornecedor",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_emissao"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="erp_ordemco_tenant__70947f_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "fornecedor"], name="erp_ordemco_tenant__509cd4_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "numero"), name="uniq_ordem_compra_numero_per_tenant"
                    )
                ],
            },
        ),
    ]
