# Generated by Django 5.2.17 on 2026-09-23 23:26

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalNotaFiscal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(max_length=50)),
                ("cliente", models.CharField(blank=True, max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("cfop", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("autorizada", "Autorizada"),
                            ("pendente", "Pendente"),
                            ("cancelada", "Cancelada"),
                            ("denegada", "Denegada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("emissao", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical nota fiscal",
                "verbose_name_plural": "historical nota fiscals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalObrigacaoFiscal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("orgao", models.CharField(blank=True, max_length=100)),
                ("vencimento", models.DateField()),
                ("competencia", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("entregue", "Entregue"),
                            ("vencida", "Vencida"),
                            ("agendada", "Agendada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical obrigacao fiscal",
                "verbose_name_plural": "historical obrigacao fiscals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="NotaFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(max_length=50)),
                ("cliente", models.CharField(blank=True, max_length=200)),
                ("valor", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("cfop", models.CharField(blank=True, max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("autorizada", "Autorizada"),
                            ("pendente", "Pendente"),
                            ("cancelada", "Cancelada"),
                            ("denegada", "Denegada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("emissao", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-emissao"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="erp_notafis_tenant__c5563b_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "emissao"], name="erp_notafis_tenant__b4f6d8_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "numero"), name="uniq_nf_numero_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ObrigacaoFiscal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("orgao", models.CharField(blank=True, max_length=100)),
                ("vencimento", models.DateField()),
                ("competencia", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("entregue", "Entregue"),
                            ("vencida", "Vencida"),
                            ("agendada", "Agendada"),
                        ],
                        default="pendente",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["vencimento"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="erp_obrigac_tenant__bdb89c_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "vencimento"], name="erp_obrigac_tenant__a74aa9_idx"
                    ),
                ],
            },
        ),
    ]
