# Generated by Django 5.2.17 on 2026-09-23 23:49

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0002_historicalnotafiscal_historicalobrigacaofiscal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BalancetePeriodo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("competencia", models.CharField(max_length=7)),
                ("ativo_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("passivo_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "patrimonio_liquido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "ordering": ["-competencia"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "competencia"], name="erp_balance_tenant__578a6f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "competencia"),
                        name="uniq_balancete_competencia_per_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBalancetePeriodo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("competencia", models.CharField(max_length=7)),
                ("ativo_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("passivo_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "patrimonio_liquido",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical balancete periodo",
                "verbose_name_plural": "historical balancete periodos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLinhaDRE",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("conta", models.CharField(max_length=200)),
                ("valor_atual", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("valor_anterior", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("receita", "Receita"),
                            ("deducao", "Dedução"),
                            ("subtotal", "Subtotal"),
                            ("custo", "Custo"),
                            ("despesa", "Despesa"),
                            ("imposto", "Imposto"),
                            ("resultado", "Resultado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("competencia", models.CharField(max_length=7)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical linha dre",
                "verbose_name_plural": "historical linha dres",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LinhaDRE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("conta", models.CharField(max_length=200)),
                ("valor_atual", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("valor_anterior", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("receita", "Receita"),
                            ("deducao", "Dedução"),
                            ("subtotal", "Subtotal"),
                            ("custo", "Custo"),
                            ("despesa", "Despesa"),
                            ("imposto", "Imposto"),
                            ("resultado", "Resultado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("competencia", models.CharField(max_length=7)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["competencia", "ordem"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "competencia"], name="erp_linhadr_tenant__e49dfc_idx"
                    )
                ],
            },
        ),
    ]
