# Generated by Django 5.2.17 on 2026-09-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0005_historicalmovimentacaoestoque_movimentacaoestoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalitemestoque",
            name="custo_medio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="historicalitemestoque",
            name="data_ultima_compra",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalmovimentacaoestoque",
            name="valor_unitario",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name="itemestoque",
            name="custo_medio",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="itemestoque",
            name="data_ultima_compra",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movimentacaoestoque",
            name="valor_unitario",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
