# Generated by Django 5.2.17 on 2026-09-26 04:24

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


def preencher_codigos(apps, schema_editor):
    """Fornecedores que já existiam ganham código F00001, F00002... por tenant."""
    Parceiro = apps.get_model("erp", "ParceiroNegocio")
    prefixo = {"cliente": "C", "fornecedor": "F", "lead": "L"}
    contadores = {}
    for p in Parceiro.objects.filter(codigo="").order_by("tenant_id", "id"):
        chave = (p.tenant_id, p.tipo)
        contadores[chave] = contadores.get(chave, 0) + 1
        p.codigo = f"{prefixo.get(p.tipo, 'P')}{contadores[chave]:05d}"
        p.save(update_fields=["codigo"])


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0014_tokens_estimated"),
        ("controladoria", "0002_alertaconformidade_updated_at_centrocusto_updated_at_and_more"),
        ("crm", "0012_sera_contrato"),
        ("erp", "0007_fornecedor_vira_parceiro_negocio"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContratoServico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(blank=True, max_length=30)),
                ("nome_projeto", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("com_material", models.BooleanField(default=False)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "periodicidade",
                    models.CharField(
                        choices=[
                            ("unica", "Parcela única"),
                            ("mensal", "Mensal"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        default="mensal",
                        max_length=12,
                    ),
                ),
                ("dia_vencimento", models.PositiveSmallIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso"),
                            ("encerrado", "Encerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Contrato de serviço",
                "verbose_name_plural": "Contratos de serviço",
                "ordering": ["-data_inicio", "-id"],
            },
        ),
        migrations.CreateModel(
            name="DadosEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("razao_social", models.CharField(blank=True, max_length=200)),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("inscricao_municipal", models.CharField(blank=True, max_length=30)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                (
                    "regime_tributario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mei", "MEI"),
                            ("simples", "Simples Nacional"),
                            ("presumido", "Lucro Presumido"),
                            ("real", "Lucro Real"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=10)),
                ("logradouro", models.CharField(blank=True, max_length=200)),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("municipio", models.CharField(blank=True, max_length=100)),
                ("uf", models.CharField(blank=True, max_length=2)),
                ("codigo_municipio_ibge", models.CharField(blank=True, max_length=7)),
                ("codigo_servico_padrao", models.CharField(blank=True, max_length=20)),
                (
                    "aliquota_iss_padrao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("serie_nfse", models.CharField(default="1", max_length=5)),
                ("email_fiscal", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "verbose_name": "Dados da empresa",
                "verbose_name_plural": "Dados da empresa",
            },
        ),
        migrations.CreateModel(
            name="HistoricalContratoServico",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.CharField(blank=True, max_length=30)),
                ("nome_projeto", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                ("com_material", models.BooleanField(default=False)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("valor_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "periodicidade",
                    models.CharField(
                        choices=[
                            ("unica", "Parcela única"),
                            ("mensal", "Mensal"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        default="mensal",
                        max_length=12,
                    ),
                ),
                ("dia_vencimento", models.PositiveSmallIntegerField(default=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("ativo", "Ativo"),
                            ("suspenso", "Suspenso"),
                            ("encerrado", "Encerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Contrato de serviço",
                "verbose_name_plural": "historical Contratos de serviço",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDadosEmpresa",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("razao_social", models.CharField(blank=True, max_length=200)),
                ("nome_fantasia", models.CharField(blank=True, max_length=200)),
                ("cnpj", models.CharField(blank=True, max_length=20)),
                ("inscricao_municipal", models.CharField(blank=True, max_length=30)),
                ("inscricao_estadual", models.CharField(blank=True, max_length=30)),
                (
                    "regime_tributario",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("mei", "MEI"),
                            ("simples", "Simples Nacional"),
                            ("presumido", "Lucro Presumido"),
                            ("real", "Lucro Real"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cep", models.CharField(blank=True, max_length=10)),
                ("logradouro", models.CharField(blank=True, max_length=200)),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("bairro", models.CharField(blank=True, max_length=100)),
                ("municipio", models.CharField(blank=True, max_length=100)),
                ("uf", models.CharField(blank=True, max_length=2)),
                ("codigo_municipio_ibge", models.CharField(blank=True, max_length=7)),
                ("codigo_servico_padrao", models.CharField(blank=True, max_length=20)),
                (
                    "aliquota_iss_padrao",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("serie_nfse", models.CharField(default="1", max_length=5)),
                ("email_fiscal", models.EmailField(blank=True, max_length=254)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Dados da empresa",
                "verbose_name_plural": "historical Dados da empresa",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalItemContrato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("servico", "Serviço"), ("material", "Material")],
                        default="servico",
                        max_length=10,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("quantidade", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("valor_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "quantidade_baixada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical item contrato",
                "verbose_name_plural": "historical item contratos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ItemContrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("servico", "Serviço"), ("material", "Material")],
                        default="servico",
                        max_length=10,
                    ),
                ),
                ("descricao", models.CharField(max_length=255)),
                ("quantidade", models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ("valor_unitario", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "quantidade_baixada",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AlterModelOptions(
            name="historicalparceironegocio",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Parceiro de negócio",
                "verbose_name_plural": "historical Parceiros de negócio",
            },
        ),
        migrations.AlterModelOptions(
            name="parceironegocio",
            options={
                "ordering": ["nome"],
                "verbose_name": "Parceiro de negócio",
                "verbose_name_plural": "Parceiros de negócio",
            },
        ),
        migrations.RenameIndex(
            model_name="parceironegocio",
            new_name="erp_parceir_tenant__87b2db_idx",
            old_name="erp_fornece_tenant__855718_idx",
        ),
        migrations.AddField(
            model_name="funcionario",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionarios",
                to="controladoria.centrocusto",
            ),
        ),
        migrations.AddField(
            model_name="funcionario",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funcionarios",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="historicalfuncionario",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="controladoria.centrocusto",
            ),
        ),
        migrations.AddField(
            model_name="historicalfuncionario",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="historicalitemestoque",
            name="codigo_servico",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalitemestoque",
            name="ncm",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="historicalitemestoque",
            name="preco_venda",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="historicalitemestoque",
            name="tipo_item",
            field=models.CharField(
                choices=[("material", "Material"), ("servico", "Serviço")],
                default="material",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="controladoria.centrocusto",
            ),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="origem",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.project",
            ),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="referencia_origem",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="aliquota_iss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="chave_acesso",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="codigo_servico",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="discriminacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="lancamento",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.lancamentofinanceiro",
            ),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="serie",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="tipo",
            field=models.CharField(
                choices=[("nfse", "NFS-e (serviço)"), ("nfe", "NF-e (produto)")],
                default="nfse",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="valor_iss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="cep",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="codigo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="codigo_municipio_ibge",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="complemento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="inscricao_estadual",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="inscricao_municipal",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="logradouro",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="municipio",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="nome_fantasia",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="numero",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="tipo",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("fornecedor", "Fornecedor"), ("lead", "Lead")],
                default="fornecedor",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="historicalparceironegocio",
            name="uf",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name="itemestoque",
            name="codigo_servico",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="itemestoque",
            name="ncm",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="itemestoque",
            name="preco_venda",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="itemestoque",
            name="tipo_item",
            field=models.CharField(
                choices=[("material", "Material"), ("servico", "Serviço")],
                default="material",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lancamentos_erp",
                to="controladoria.centrocusto",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="data_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="origem",
            field=models.CharField(default="manual", max_length=20),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lancamentos",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lancamentos_erp",
                to="crm.project",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="referencia_origem",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lancamentos_erp",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="aliquota_iss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="chave_acesso",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="codigo_servico",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="discriminacao",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="lancamento",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_fiscais",
                to="erp.lancamentofinanceiro",
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="notas_fiscais",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="serie",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="tipo",
            field=models.CharField(
                choices=[("nfse", "NFS-e (serviço)"), ("nfe", "NF-e (produto)")],
                default="nfse",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="valor_iss",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="bairro",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="cep",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="codigo",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="codigo_municipio_ibge",
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="complemento",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="inscricao_estadual",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="inscricao_municipal",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="logradouro",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="municipio",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="nome_fantasia",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="numero",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="tipo",
            field=models.CharField(
                choices=[("cliente", "Cliente"), ("fornecedor", "Fornecedor"), ("lead", "Lead")],
                default="fornecedor",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="parceironegocio",
            name="uf",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="historicalitemestoque",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("un", "Unidade"),
                    ("kg", "Kg"),
                    ("m", "Metro"),
                    ("l", "Litro"),
                    ("cx", "Caixa"),
                    ("pc", "Peça"),
                    ("h", "Hora"),
                    ("mes", "Mês"),
                    ("sv", "Serviço"),
                ],
                default="un",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="historicalnotafiscal",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho (não transmitida)"),
                    ("autorizada", "Autorizada"),
                    ("pendente", "Pendente"),
                    ("cancelada", "Cancelada"),
                    ("denegada", "Denegada"),
                ],
                default="pendente",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="itemestoque",
            name="unidade",
            field=models.CharField(
                choices=[
                    ("un", "Unidade"),
                    ("kg", "Kg"),
                    ("m", "Metro"),
                    ("l", "Litro"),
                    ("cx", "Caixa"),
                    ("pc", "Peça"),
                    ("h", "Hora"),
                    ("mes", "Mês"),
                    ("sv", "Serviço"),
                ],
                default="un",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho (não transmitida)"),
                    ("autorizada", "Autorizada"),
                    ("pendente", "Pendente"),
                    ("cancelada", "Cancelada"),
                    ("denegada", "Denegada"),
                ],
                default="pendente",
                max_length=15,
            ),
        ),
        migrations.AddIndex(
            model_name="parceironegocio",
            index=models.Index(fields=["tenant_id", "tipo"], name="erp_parceir_tenant__ce423c_idx"),
        ),
        migrations.AddConstraint(
            model_name="parceironegocio",
            constraint=models.UniqueConstraint(
                condition=models.Q(("codigo", ""), _negated=True),
                fields=("tenant_id", "codigo"),
                name="uniq_parceiro_codigo_per_tenant",
            ),
        ),
        migrations.AddField(
            model_name="contratoservico",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_erp",
                to="controladoria.centrocusto",
            ),
        ),
        migrations.AddField(
            model_name="contratoservico",
            name="parceiro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contratos",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="contratoservico",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_erp",
                to="crm.project",
            ),
        ),
        migrations.AddField(
            model_name="contratoservico",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_erp",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="historicallancamentofinanceiro",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.contratoservico",
            ),
        ),
        migrations.AddField(
            model_name="historicalnotafiscal",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.contratoservico",
            ),
        ),
        migrations.AddField(
            model_name="lancamentofinanceiro",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lancamentos",
                to="erp.contratoservico",
            ),
        ),
        migrations.AddField(
            model_name="notafiscal",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notas_fiscais",
                to="erp.contratoservico",
            ),
        ),
        migrations.AddIndex(
            model_name="lancamentofinanceiro",
            index=models.Index(
                fields=["tenant_id", "contrato"], name="erp_lancame_tenant__c045e2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lancamentofinanceiro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("referencia_origem", ""), _negated=True),
                fields=("tenant_id", "referencia_origem"),
                name="uniq_lancamento_referencia_origem",
            ),
        ),
        migrations.AddConstraint(
            model_name="dadosempresa",
            constraint=models.UniqueConstraint(
                fields=("tenant_id",), name="uniq_dados_empresa_per_tenant"
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoservico",
            name="centro_custo",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="controladoria.centrocusto",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoservico",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoservico",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoservico",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.project",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontratoservico",
            name="setor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="agency.sector",
            ),
        ),
        migrations.AddField(
            model_name="historicaldadosempresa",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalitemcontrato",
            name="contrato",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.contratoservico",
            ),
        ),
        migrations.AddField(
            model_name="historicalitemcontrato",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalitemcontrato",
            name="item",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.itemestoque",
            ),
        ),
        migrations.AddField(
            model_name="itemcontrato",
            name="contrato",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="itens",
                to="erp.contratoservico",
            ),
        ),
        migrations.AddField(
            model_name="itemcontrato",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_contrato",
                to="erp.itemestoque",
            ),
        ),
        migrations.AddIndex(
            model_name="contratoservico",
            index=models.Index(
                fields=["tenant_id", "status"], name="erp_contrat_tenant__182dae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contratoservico",
            index=models.Index(
                fields=["tenant_id", "data_fim"], name="erp_contrat_tenant__496d35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contratoservico",
            index=models.Index(
                fields=["tenant_id", "projeto"], name="erp_contrat_tenant__6f036c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="contratoservico",
            constraint=models.UniqueConstraint(
                condition=models.Q(("numero", ""), _negated=True),
                fields=("tenant_id", "numero"),
                name="uniq_contrato_numero_per_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratoservico",
            constraint=models.CheckConstraint(
                condition=models.Q(("data_fim__gte", models.F("data_inicio"))),
                name="contrato_fim_depois_do_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratoservico",
            constraint=models.CheckConstraint(
                condition=models.Q(("dia_vencimento__gte", 1), ("dia_vencimento__lte", 28)),
                name="contrato_dia_vencimento_valido",
            ),
        ),
        migrations.AddIndex(
            model_name="itemcontrato",
            index=models.Index(
                fields=["tenant_id", "contrato"], name="erp_itemcon_tenant__eb395d_idx"
            ),
        ),
        migrations.RunPython(preencher_codigos, migrations.RunPython.noop),
    ]
