# Generated by Django 5.2.17 on 2026-09-26 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0008_erp_sap_b1_contratos_parceiros"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnotafiscal",
            name="emissao",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="historicalordemcompra",
            name="data_emissao",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="notafiscal",
            name="emissao",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="ordemcompra",
            name="data_emissao",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
