# Generated by Django 5.2.17 on 2026-09-26 18:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Batimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nome", models.CharField(max_length=200, unique=True)),
                ("em", models.DateTimeField(default=django.utils.timezone.now)),
                ("dados", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="EventoErro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("impressao", models.CharField(max_length=40, unique=True)),
                ("logger", models.CharField(max_length=200)),
                ("nivel", models.CharField(max_length=20)),
                ("mensagem", models.TextField()),
                ("trace", models.TextField(blank=True)),
                ("origem", models.CharField(blank=True, max_length=300)),
                ("ocorrencias", models.PositiveIntegerField(default=1)),
                ("primeiro", models.DateTimeField(default=django.utils.timezone.now)),
                ("ultimo", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("resolvido", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-ultimo"],
            },
        ),
        migrations.CreateModel(
            name="Amostra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(default=uuid.UUID("00000000-0000-0000-0000-000000000000")),
                ),
                ("chave", models.CharField(max_length=150)),
                ("em", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Funcionando"),
                            ("alerta", "Atenção"),
                            ("falha", "Fora do ar"),
                            ("desconhecido", "Sem dados"),
                        ],
                        max_length=15,
                    ),
                ),
                ("ms", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "chave", "em"], name="observabili_tenant__797a94_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EstadoComponente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, default=uuid.UUID("00000000-0000-0000-0000-000000000000")
                    ),
                ),
                ("chave", models.CharField(max_length=150)),
                ("grupo", models.CharField(max_length=30)),
                ("nome", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Funcionando"),
                            ("alerta", "Atenção"),
                            ("falha", "Fora do ar"),
                            ("desconhecido", "Sem dados"),
                        ],
                        default="desconhecido",
                        max_length=15,
                    ),
                ),
                ("detalhe", models.TextField(blank=True)),
                (
                    "causa",
                    models.TextField(blank=True, help_text="Por que (em português, pra gente)."),
                ),
                ("acao", models.TextField(blank=True, help_text="O que fazer.")),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("ms", models.PositiveIntegerField(blank=True, null=True)),
                ("falhas_seguidas", models.PositiveIntegerField(default=0)),
                ("desde", models.DateTimeField(default=django.utils.timezone.now)),
                ("verificado_em", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["grupo", "nome"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "chave"), name="estado_unico_por_chave"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, default=uuid.UUID("00000000-0000-0000-0000-000000000000")
                    ),
                ),
                ("chave", models.CharField(max_length=150)),
                ("grupo", models.CharField(max_length=30)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "gravidade",
                    models.CharField(
                        choices=[("critica", "Crítica"), ("alta", "Alta"), ("media", "Média")],
                        default="alta",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("aberto", "Aberto"), ("resolvido", "Resolvido")],
                        default="aberto",
                        max_length=15,
                    ),
                ),
                ("aberto_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("resolvido_em", models.DateTimeField(blank=True, null=True)),
                ("detalhe", models.TextField(blank=True)),
                ("causa", models.TextField(blank=True)),
                ("acao", models.TextField(blank=True)),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("diagnostico", models.JSONField(blank=True, default=dict)),
                ("chamado_id", models.PositiveIntegerField(blank=True, null=True)),
                ("reconhecido_por", models.CharField(blank=True, max_length=255)),
                ("reconhecido_em", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-aberto_em"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="observabili_tenant__f4c784_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Metrica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(
                        db_index=True, default=uuid.UUID("00000000-0000-0000-0000-000000000000")
                    ),
                ),
                ("minuto", models.DateTimeField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("api", "API"), ("ia", "IA"), ("http", "Saída HTTP")],
                        max_length=10,
                    ),
                ),
                ("chave", models.CharField(max_length=200)),
                ("total", models.PositiveIntegerField(default=0)),
                ("erros", models.PositiveIntegerField(default=0)),
                ("erros_cliente", models.PositiveIntegerField(default=0)),
                ("ms_total", models.PositiveBigIntegerField(default=0)),
                ("ms_max", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tipo", "minuto"], name="observabili_tipo_e6a0aa_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "minuto", "tipo", "chave"),
                        name="metrica_unica_por_minuto",
                    )
                ],
            },
        ),
    ]
