# Generated by Django 5.2.17 on 2026-09-25 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0003_alter_historicalknowledgesource_source_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalknowledgesource",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
