# Generated by Django 5.2.17 on 2026-09-26 12:12

import django.db.models.deletion
import django.utils.timezone
import json
import uuid

from django.conf import settings
from django.db import migrations, models

# Mesma lista de ingestion.connectors.secrets.SECRET_FIELDS (cópia fixa: migração
# não importa código que pode mudar depois).
SECRET_FIELDS = {
    "rest_api": ["api_key"],
    "google_sheets": ["service_account_json"],
    "slack": ["bot_token"],
    "notion": ["integration_token"],
    "hubspot": ["api_key"],
    "salesforce": ["client_secret"],
    "email": ["password"],
    "webhook": ["secret"],
    "sql": ["password"],
}


def preencher_e_cifrar(apps, schema_editor):
    """public_id pra todo conector; segredos em texto puro saem do config."""
    Source = apps.get_model("ingestion", "KnowledgeSource")
    fernet = None
    if getattr(settings, "ENCRYPTION_KEY", ""):
        from cryptography.fernet import Fernet

        key = settings.ENCRYPTION_KEY
        fernet = Fernet(key.encode() if isinstance(key, str) else key)
    for src in Source.objects.all():
        src.public_id = uuid.uuid4()
        fields = ["public_id"]
        config = dict(src.config or {})
        secrets = {k: config[k] for k in SECRET_FIELDS.get(src.source_type, []) if config.get(k)}
        if secrets and fernet is not None:
            # Sem ENCRYPTION_KEY o segredo fica onde está e muda no próximo save pela API
            for k in secrets:
                config.pop(k)
            src.config = config
            src.secret_config = fernet.encrypt(json.dumps(secrets).encode()).decode()
            fields += ["config", "secret_config"]
        src.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0004_historicalknowledgesource_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalknowledgesource",
            name="last_sync_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalknowledgesource",
            name="last_sync_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nunca sincronizado"),
                    ("running", "Sincronizando"),
                    ("ok", "OK"),
                    ("error", "Erro"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalknowledgesource",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="historicalknowledgesource",
            name="secret_config",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalknowledgesource",
            name="sync_interval_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="last_sync_message",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="last_sync_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Nunca sincronizado"),
                    ("running", "Sincronizando"),
                    ("ok", "OK"),
                    ("error", "Erro"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="public_id",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="secret_config",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="knowledgesource",
            name="sync_interval_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SourceSyncRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("schedule", "Agendado"),
                            ("webhook", "Webhook"),
                        ],
                        default="manual",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("running", "Rodando"), ("ok", "OK"), ("error", "Erro")],
                        default="running",
                        max_length=10,
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("unchanged", models.PositiveIntegerField(default=0)),
                ("removed", models.PositiveIntegerField(default=0)),
                ("message", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_runs",
                        to="ingestion.knowledgesource",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "source", "-started_at"],
                        name="ingestion_s_tenant__56b346_idx",
                    )
                ],
            },
        ),
            migrations.RunPython(preencher_e_cifrar, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="knowledgesource",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="historicalknowledgesource",
            name="public_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
