# Generated by Django 5.2.17 on 2026-09-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0005_conectores_segredos_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalknowledgesource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("obsidian", "Vault do Obsidian"),
                    ("upload", "Upload manual"),
                    ("manual", "Base manual"),
                    ("url", "URL / Web"),
                    ("api", "API externa"),
                    ("rest_api", "REST API"),
                    ("sql", "Banco SQL"),
                    ("google_sheets", "Google Sheets"),
                    ("slack", "Slack"),
                    ("webhook", "Webhook"),
                    ("email", "E-mail (IMAP)"),
                    ("notion", "Notion"),
                    ("hubspot", "HubSpot"),
                    ("salesforce", "Salesforce"),
                    ("mcp", "Servidor MCP"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="knowledgesource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("obsidian", "Vault do Obsidian"),
                    ("upload", "Upload manual"),
                    ("manual", "Base manual"),
                    ("url", "URL / Web"),
                    ("api", "API externa"),
                    ("rest_api", "REST API"),
                    ("sql", "Banco SQL"),
                    ("google_sheets", "Google Sheets"),
                    ("slack", "Slack"),
                    ("webhook", "Webhook"),
                    ("email", "E-mail (IMAP)"),
                    ("notion", "Notion"),
                    ("hubspot", "HubSpot"),
                    ("salesforce", "Salesforce"),
                    ("mcp", "Servidor MCP"),
                ],
                max_length=20,
            ),
        ),
    ]
