# Generated by Django 5.2.17 on 2026-08-24 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (local, sem API key)'), ('openai', 'OpenAI (ou compatível)'), ('anthropic', 'Anthropic (Claude)'), ('groq', 'Groq'), ('openrouter', 'OpenRouter (gateway multi-modelo)')], max_length=20)),
                ('label', models.CharField(blank=True, help_text="Nome livre, ex: 'Groq produção' — só para organização no admin.", max_length=100)),
                ('base_url', models.URLField(blank=True, help_text='Sobrescreve a URL padrão do provedor (útil para proxies/self-host).')),
                ('_encrypted_api_key', models.TextField(blank=True, db_column='api_key_encrypted')),
                ('default_model', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de Provedor de IA',
                'verbose_name_plural': 'Credenciais de Provedores de IA',
                'indexes': [models.Index(fields=['tenant_id', 'provider', 'is_active'], name='harness_aip_tenant__e0e6e0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant_id', 'provider'), name='uniq_active_credential_per_tenant_provider')],
            },
        ),
    ]
