# Generated by Django 5.2.17 on 2026-09-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaloportunidade",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospeccao", "Prospecção"),
                    ("qualificacao", "Qualificação"),
                    ("proposta", "Proposta"),
                    ("negociacao", "Negociação"),
                    ("ganho", "Ganho"),
                    ("perdido", "Perdido"),
                ],
                default="prospeccao",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="oportunidade",
            name="status",
            field=models.CharField(
                choices=[
                    ("prospeccao", "Prospecção"),
                    ("qualificacao", "Qualificação"),
                    ("proposta", "Proposta"),
                    ("negociacao", "Negociação"),
                    ("ganho", "Ganho"),
                    ("perdido", "Perdido"),
                ],
                default="prospeccao",
                max_length=15,
            ),
        ),
    ]
