# Generated by Django 5.2.17 on 2026-09-24 12:37

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_update_oportunidade_status_choices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPipeline",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("name", models.CharField(default="Pipeline Comercial", max_length=150)),
                ("is_default", models.BooleanField(default=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pipeline",
                "verbose_name_plural": "historical pipelines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LeadMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "Usuário / Lead"),
                            ("agent", "Agente"),
                            ("system", "Sistema"),
                        ],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("name", models.CharField(default="Pipeline Comercial", max_length=150)),
                ("is_default", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "main_stage",
                    models.CharField(
                        choices=[("lead", "Lead"), ("deal", "Deal"), ("project", "Projeto")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                ("color", models.CharField(default="blue", max_length=30)),
                ("is_won", models.BooleanField(default=False)),
                ("is_lost", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["main_stage", "position"],
            },
        ),
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["position", "-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="lead",
            name="crm_lead_tenant__3e1c47_idx",
        ),
        migrations.RemoveField(
            model_name="historicallead",
            name="status",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="status",
        ),
        migrations.AddField(
            model_name="historicallead",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lead",
            name="position",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalpipeline",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="leadmessage",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="crm.lead"
            ),
        ),
        migrations.AddIndex(
            model_name="pipeline",
            index=models.Index(fields=["tenant_id"], name="crm_pipelin_tenant__595747_idx"),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="crm.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="stage",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="crm.pipeline",
            ),
        ),
        migrations.AddField(
            model_name="historicallead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="crm.stage",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="crm.stage",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["tenant_id", "stage"], name="crm_lead_tenant__5bb28f_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant_id", "pipeline"], name="crm_lead_tenant__86037d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leadmessage",
            index=models.Index(fields=["tenant_id", "lead"], name="crm_leadmes_tenant__f637db_idx"),
        ),
        migrations.AddIndex(
            model_name="stage",
            index=models.Index(
                fields=["tenant_id", "pipeline", "main_stage"], name="crm_stage_tenant__809190_idx"
            ),
        ),
    ]
