# Generated by Django 5.2.17 on 2026-09-24 13:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_historicalpipeline_leadmessage_pipeline_stage_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChannelConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp (Evolution API)"),
                            ("telegram", "Telegram Bot"),
                            ("landing_page", "Landing Page"),
                            ("meta_ads", "Meta Lead Ads (Facebook/Instagram)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("_api_key", models.TextField(blank=True, db_column="api_key_encrypted")),
                (
                    "config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='WhatsApp: {"instance": "...", "server_url": "http://..."}. Telegram: {"bot_username": "..."}. Meta Ads: {"page_id": "...", "verify_token": "..."}.',
                    ),
                ),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de Canal",
                "verbose_name_plural": "Configurações de Canais",
            },
        ),
        migrations.AddField(
            model_name="historicallead",
            name="channel_ref",
            field=models.CharField(
                blank=True,
                help_text="Identificador único do lead no canal de origem (ex: número WhatsApp, Telegram chat_id).",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="channel_ref",
            field=models.CharField(
                blank=True,
                help_text="Identificador único do lead no canal de origem (ex: número WhatsApp, Telegram chat_id).",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicallead",
            name="origem",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("indicacao", "Indicação"),
                    ("social", "Redes sociais"),
                    ("evento", "Evento"),
                    ("cold_outreach", "Cold outreach"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("landing_page", "Landing Page"),
                    ("meta_ads", "Meta Ads (Facebook/Instagram)"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="origem",
            field=models.CharField(
                choices=[
                    ("site", "Site"),
                    ("indicacao", "Indicação"),
                    ("social", "Redes sociais"),
                    ("evento", "Evento"),
                    ("cold_outreach", "Cold outreach"),
                    ("whatsapp", "WhatsApp"),
                    ("telegram", "Telegram"),
                    ("landing_page", "Landing Page"),
                    ("meta_ads", "Meta Ads (Facebook/Instagram)"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(
                fields=["tenant_id", "channel_ref"], name="crm_lead_tenant__385ee2_idx"
            ),
        ),
        migrations.AddField(
            model_name="channelconfig",
            name="target_pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="channel_configs",
                to="crm.pipeline",
            ),
        ),
        migrations.AddIndex(
            model_name="channelconfig",
            index=models.Index(
                fields=["tenant_id", "channel", "is_active"], name="crm_channel_tenant__a8388e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="channelconfig",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant_id", "channel"),
                name="uniq_active_channel_per_tenant",
            ),
        ),
    ]
