# Generated by Django 5.2.17 on 2026-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_add_channel_ref_channelconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelconfig",
            name="quick_replies",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Lista de sugestões de perguntas. Ex: ["Ver preços", "Falar com atendente", "Saber mais"]',
            ),
        ),
        migrations.AddField(
            model_name="channelconfig",
            name="welcome_message",
            field=models.TextField(
                blank=True,
                help_text="Mensagem enviada automaticamente quando o lead entra em contato pela primeira vez.",
            ),
        ),
    ]
