# Generated by Django 5.2.17 on 2026-09-24 20:16

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_lead_outcome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="oportunidade",
            name="lead",
        ),
        migrations.AlterField(
            model_name="channelconfig",
            name="config",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="channelconfig",
            name="quick_replies",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="channelconfig",
            name="welcome_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicallead",
            name="channel_ref",
            field=models.CharField(
                blank=True,
                help_text="Identificador único do lead no canal de origem.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="historicallead",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("convertido", "Convertido em Deal"),
                    ("perdido", "Perdido"),
                    ("cancelado", "Cancelado"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="channel_ref",
            field=models.CharField(
                blank=True,
                help_text="Identificador único do lead no canal de origem.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="outcome",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "—"),
                    ("convertido", "Convertido em Deal"),
                    ("perdido", "Perdido"),
                    ("cancelado", "Cancelado"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[("lead", "Lead"), ("deal", "Deal"), ("project", "Projeto")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "key",
                    models.SlugField(
                        help_text="Identificador único do campo (snake_case).", max_length=100
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Texto"),
                            ("textarea", "Texto longo"),
                            ("number", "Número"),
                            ("currency", "Moeda"),
                            ("date", "Data"),
                            ("select", "Seleção"),
                            ("multiselect", "Multi-seleção"),
                            ("checkbox", "Checkbox"),
                            ("email", "E-mail"),
                            ("phone", "Telefone"),
                            ("url", "URL"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Para select/multiselect: lista de strings. Ex: ["Opção A", "Opção B"]',
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["entity_type", "position"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "entity_type", "is_active"],
                        name="crm_customf_tenant__96a3b6_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "entity_type", "key"),
                        name="uniq_custom_field_key_per_entity_tenant",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CustomFieldValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.PositiveIntegerField()),
                ("value", models.JSONField(blank=True, null=True)),
                (
                    "field_def",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="crm.customfielddefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("titulo", models.CharField(max_length=255)),
                ("empresa", models.CharField(blank=True, max_length=200)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                (
                    "valor",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("moeda", models.CharField(blank=True, default="BRL", max_length=10)),
                ("data_fechamento_previsto", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("ganho", "Ganho"),
                            ("contrato_assinado", "Contrato Assinado"),
                            ("perdido", "Perdido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.lead",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.pipeline",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deals",
                        to="crm.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDeal",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("titulo", models.CharField(max_length=255)),
                ("empresa", models.CharField(blank=True, max_length=200)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                (
                    "valor",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("moeda", models.CharField(blank=True, default="BRL", max_length=10)),
                ("data_fechamento_previsto", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("ganho", "Ganho"),
                            ("contrato_assinado", "Contrato Assinado"),
                            ("perdido", "Perdido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.lead",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.pipeline",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical deal",
                "verbose_name_plural": "historical deals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("titulo", models.CharField(max_length=255)),
                ("empresa", models.CharField(blank=True, max_length=200)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_previsto", models.DateField(blank=True, null=True)),
                ("data_fim_realizado", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("concluido", "Concluído"),
                            ("pausado", "Pausado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.deal",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.lead",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.pipeline",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="crm.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project",
                "verbose_name_plural": "historical projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("titulo", models.CharField(max_length=255)),
                ("empresa", models.CharField(blank=True, max_length=200)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_fim_previsto", models.DateField(blank=True, null=True)),
                ("data_fim_realizado", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("concluido", "Concluído"),
                            ("pausado", "Pausado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "deal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="crm.deal",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="crm.lead",
                    ),
                ),
                (
                    "pipeline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="crm.pipeline",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="crm.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="HistoricalOportunidade",
        ),
        migrations.DeleteModel(
            name="Oportunidade",
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["tenant_id", "entity_type", "entity_id"],
                name="crm_customf_tenant__e1398b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="customfieldvalue",
            index=models.Index(
                fields=["tenant_id", "field_def"], name="crm_customf_tenant__f88371_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="customfieldvalue",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "field_def", "entity_type", "entity_id"),
                name="uniq_custom_field_value_per_entity",
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "stage"], name="crm_deal_tenant__ee7cee_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant_id", "pipeline"], name="crm_deal_tenant__334062_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(fields=["tenant_id", "lead"], name="crm_deal_tenant__35044f_idx"),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["tenant_id", "responsavel"], name="crm_deal_tenant__0b7ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant_id", "stage"], name="crm_project_tenant__541319_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["tenant_id", "pipeline"], name="crm_project_tenant__ab80a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["tenant_id", "deal"], name="crm_project_tenant__e4c056_idx"),
        ),
    ]
