# Generated by Django 5.2.17 on 2026-09-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_deal_project_customfields"),
    ]

    operations = [
        migrations.AddField(
            model_name="channelconfig",
            name="trigger_phrases",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
