# Generated by Django 5.2.17 on 2026-09-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_atividadecrm_updated_at_contato_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="contrato_com_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="deal",
            name="sera_contrato",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeal",
            name="contrato_com_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaldeal",
            name="sera_contrato",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="contrato_com_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="sera_contrato",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="contrato_com_material",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="sera_contrato",
            field=models.BooleanField(default=False),
        ),
    ]
