# Generated by Django 5.2.17 on 2026-08-24 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('session_id', models.CharField(blank=True, max_length=100)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('purpose_flags', models.JSONField(default=list)),
                ('term_version', models.CharField(db_index=True, max_length=20)),
                ('accepted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Usuário autenticado (nulo para titular anônimo/pré-cadastro).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Consentimento LGPD',
                'verbose_name_plural': 'Registros de Consentimento LGPD',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['tenant_id', 'email', 'term_version'], name='core_consen_tenant__9ba996_idx'), models.Index(fields=['tenant_id', 'user', 'term_version'], name='core_consen_tenant__d00ac4_idx')],
            },
        ),
    ]
