# Generated by Django 5.2.17 on 2026-09-23 23:26

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertaConformidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=300)),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico"),
                            ("alto", "Alto"),
                            ("medio", "Médio"),
                            ("baixo", "Baixo"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("prazo", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_analise", "Em análise"),
                            ("resolvido", "Resolvido"),
                            ("ignorado", "Ignorado"),
                        ],
                        default="aberto",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "severidade", "status"],
                        name="controlador_tenant__776be4_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CentroCusto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, max_length=30)),
                ("budget", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("realizado", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                (
                    "tendencia",
                    models.CharField(
                        choices=[
                            ("up", "Crescente"),
                            ("down", "Decrescente"),
                            ("stable", "Estável"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["nome"],
                "indexes": [
                    models.Index(fields=["tenant_id"], name="controlador_tenant__563c01_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "codigo"), name="uniq_centro_custo_codigo_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EntradaAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("usuario", models.CharField(max_length=150)),
                ("modulo", models.CharField(max_length=100)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("CREATE", "Criação"),
                            ("UPDATE", "Atualização"),
                            ("DELETE", "Exclusão"),
                            ("LOGIN", "Login"),
                            ("EXPORT", "Exportação"),
                            ("VIEW", "Visualização"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recurso", models.CharField(max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("detalhes", models.TextField(blank=True)),
                (
                    "criticidade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("critica", "Crítica"),
                        ],
                        default="baixa",
                        max_length=10,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "created_at"], name="controlador_tenant__47087b_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "modulo"], name="controlador_tenant__666e88_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "acao"], name="controlador_tenant__7c2992_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAlertaConformidade",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=300)),
                (
                    "severidade",
                    models.CharField(
                        choices=[
                            ("critico", "Crítico"),
                            ("alto", "Alto"),
                            ("medio", "Médio"),
                            ("baixo", "Baixo"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("prazo", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Aberto"),
                            ("em_analise", "Em análise"),
                            ("resolvido", "Resolvido"),
                            ("ignorado", "Ignorado"),
                        ],
                        default="aberto",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical alerta conformidade",
                "verbose_name_plural": "historical alerta conformidades",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCentroCusto",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                ("codigo", models.CharField(blank=True, max_length=30)),
                ("budget", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ("realizado", models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                (
                    "tendencia",
                    models.CharField(
                        choices=[
                            ("up", "Crescente"),
                            ("down", "Decrescente"),
                            ("stable", "Estável"),
                        ],
                        default="stable",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical centro custo",
                "verbose_name_plural": "historical centro custos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
