# Generated by Django 5.2.17 on 2026-09-25 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("controladoria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alertaconformidade",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="centrocusto",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="historicalalertaconformidade",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="historicalcentrocusto",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
