# Generated by Django 5.2.17 on 2026-08-25 00:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('provider', models.CharField(choices=[('github', 'GitHub'), ('vercel', 'Vercel'), ('render', 'Render'), ('supabase', 'Supabase')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('account_ref', models.CharField(blank=True, help_text='GitHub: organização ou usuário. Supabase: URL do projeto. Vazio = conta pessoal do token.', max_length=255)),
                ('_encrypted_token', models.TextField(blank=True, db_column='token_encrypted')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial de Serviço Externo',
                'verbose_name_plural': 'Credenciais de Serviços Externos',
                'indexes': [models.Index(fields=['tenant_id', 'provider', 'is_active'], name='integration_tenant__fad5a4_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant_id', 'provider'), name='uniq_active_service_credential_per_tenant_provider')],
            },
        ),
    ]
