# Generated by Django 5.2.17 on 2026-09-26 13:49

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0015_conectores_segredos_sync"),
        ("integrations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ServerConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("oracle", "Oracle Cloud"),
                            ("hostinger", "Hostinger"),
                            ("outro", "Outro"),
                        ],
                        default="oracle",
                        max_length=20,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("ssh_port", models.PositiveIntegerField(default=22)),
                ("username", models.CharField(blank=True, default="ubuntu", max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        blank=True,
                        help_text="Pra que serve (ex.: n8n, backend, banco).",
                        max_length=255,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("private_key_encrypted", models.TextField(blank=True)),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_ok", models.BooleanField(null=True)),
                ("last_check_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Servidor (VPS)",
                "verbose_name_plural": "Servidores (VPS)",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="servicecredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("vercel", "Vercel"),
                    ("render", "Render"),
                    ("supabase", "Supabase"),
                    ("n8n", "n8n"),
                    ("hostinger", "Hostinger"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("address", models.EmailField(blank=True, max_length=254)),
                ("display_name", models.CharField(blank=True, max_length=120)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("hostinger", "Hostinger"),
                            ("gmail", "Gmail / Google Workspace"),
                            ("outlook", "Outlook / Microsoft 365"),
                            ("custom", "Outro (SMTP próprio)"),
                        ],
                        default="hostinger",
                        max_length=20,
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255)),
                ("smtp_port", models.PositiveIntegerField(default=465)),
                (
                    "smtp_security",
                    models.CharField(
                        choices=[("ssl", "SSL/TLS"), ("starttls", "STARTTLS"), ("none", "Nenhuma")],
                        default="ssl",
                        max_length=10,
                    ),
                ),
                ("imap_host", models.CharField(blank=True, max_length=255)),
                ("imap_port", models.PositiveIntegerField(default=993)),
                (
                    "username",
                    models.CharField(
                        blank=True, help_text="Vazio = o próprio endereço.", max_length=255
                    ),
                ),
                ("password_encrypted", models.TextField(blank=True)),
                ("signature", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando configuração"),
                            ("ready", "Pronta"),
                            ("error", "Com erro"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("last_check_at", models.DateTimeField(blank=True, null=True)),
                ("last_check_message", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_accounts",
                        to="agency.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caixa de e-mail",
                "verbose_name_plural": "Caixas de e-mail",
            },
        ),
        migrations.CreateModel(
            name="HistoricalOutboundEmail",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho (aguardando aprovação)"),
                            ("sending", "Enviando"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("origin", models.CharField(blank=True, db_index=True, max_length=100)),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("approved_by", models.CharField(blank=True, max_length=150)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="integrations.emailaccount",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="agency.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical E-mail de saída",
                "verbose_name_plural": "historical E-mails de saída",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho (aguardando aprovação)"),
                            ("sending", "Enviando"),
                            ("sent", "Enviado"),
                            ("failed", "Falhou"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("origin", models.CharField(blank=True, db_index=True, max_length=100)),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("approved_by", models.CharField(blank=True, max_length=150)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("message_id", models.CharField(blank=True, max_length=255)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emails",
                        to="integrations.emailaccount",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outbound_emails",
                        to="agency.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail de saída",
                "verbose_name_plural": "E-mails de saída",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="emailaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("tenant_id", "sector"),
                name="uniq_active_email_account_per_sector",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["tenant_id", "status"], name="integration_tenant__fec27f_idx"
            ),
        ),
    ]
