# Generated by Django 5.2.17 on 2026-09-26 15:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0015_conectores_segredos_sync"),
        ("integrations", "0002_caixas_email_servidores_n8n"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailaccount",
            name="imap_last_uid",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="last_fetch_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emailaccount",
            name="last_fetch_message",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="historicaloutboundemail",
            name="written_by_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="outboundemail",
            name="written_by_ai",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="InboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("uid", models.BigIntegerField()),
                ("message_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("from_address", models.CharField(blank=True, max_length=255)),
                ("from_name", models.CharField(blank=True, max_length=255)),
                ("to", models.JSONField(blank=True, default=list)),
                ("cc", models.JSONField(blank=True, default=list)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                (
                    "received_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound",
                        to="integrations.emailaccount",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inbound_emails",
                        to="agency.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "E-mail recebido",
                "verbose_name_plural": "E-mails recebidos",
                "ordering": ["-received_at"],
            },
        ),
        migrations.AddField(
            model_name="historicaloutboundemail",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="integrations.inboundemail",
            ),
        ),
        migrations.AddField(
            model_name="outboundemail",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="integrations.inboundemail",
            ),
        ),
        migrations.AddIndex(
            model_name="inboundemail",
            index=models.Index(
                fields=["tenant_id", "sector", "is_read"], name="integration_tenant__6b0207_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="inboundemail",
            constraint=models.UniqueConstraint(
                fields=("account", "uid"), name="uniq_inbound_uid_per_account"
            ),
        ),
    ]
