# Generated by Django 5.2.17 on 2026-09-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_caixa_de_entrada"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("github", "GitHub"),
                    ("vercel", "Vercel"),
                    ("render", "Render"),
                    ("supabase", "Supabase"),
                    ("n8n", "n8n"),
                    ("hostinger", "Hostinger"),
                    ("datajud", "DataJud (CNJ)"),
                ],
                max_length=20,
            ),
        ),
    ]
