# Generated by Django 5.2.17 on 2026-09-23 21:40

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("servico", "Serviço"),
                            ("fornecimento", "Fornecimento"),
                            ("locacao", "Locação"),
                            ("parceria", "Parceria"),
                            ("nda", "NDA"),
                            ("trabalhista", "Trabalhista"),
                            ("outro", "Outro"),
                        ],
                        default="servico",
                        max_length=20,
                    ),
                ),
                ("partes", models.CharField(max_length=300)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("valor_anual", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("expirando", "Expirando"),
                            ("vencido", "Vencido"),
                            ("negociacao", "Em negociação"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="vigente",
                        max_length=20,
                    ),
                ),
                (
                    "renovacao",
                    models.CharField(
                        choices=[
                            ("automatica", "Automática"),
                            ("negociacao", "Negociação"),
                            ("nao_renovar", "Não renovar"),
                        ],
                        default="negociacao",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="juridico_co_tenant__663613_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "data_fim"], name="juridico_co_tenant__b1d67b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalContrato",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("servico", "Serviço"),
                            ("fornecimento", "Fornecimento"),
                            ("locacao", "Locação"),
                            ("parceria", "Parceria"),
                            ("nda", "NDA"),
                            ("trabalhista", "Trabalhista"),
                            ("outro", "Outro"),
                        ],
                        default="servico",
                        max_length=20,
                    ),
                ),
                ("partes", models.CharField(max_length=300)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                ("valor_anual", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("vigente", "Vigente"),
                            ("expirando", "Expirando"),
                            ("vencido", "Vencido"),
                            ("negociacao", "Em negociação"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="vigente",
                        max_length=20,
                    ),
                ),
                (
                    "renovacao",
                    models.CharField(
                        choices=[
                            ("automatica", "Automática"),
                            ("negociacao", "Negociação"),
                            ("nao_renovar", "Não renovar"),
                        ],
                        default="negociacao",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contrato",
                "verbose_name_plural": "historical contratos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProcesso",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("trabalhista", "Trabalhista"),
                            ("civel", "Cível"),
                            ("criminal", "Criminal"),
                            ("tributario", "Tributário"),
                            ("contratual", "Contratual"),
                            ("regulatorio", "Regulatório"),
                            ("outro", "Outro"),
                        ],
                        default="civel",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("ganho", "Ganho"),
                            ("perdido", "Perdido"),
                            ("acordo", "Acordo"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="em_andamento",
                        max_length=20,
                    ),
                ),
                ("parte", models.CharField(max_length=200)),
                ("advogado", models.CharField(blank=True, max_length=200)),
                ("foro", models.CharField(blank=True, max_length=100)),
                (
                    "risco",
                    models.CharField(
                        choices=[("alto", "Alto"), ("medio", "Médio"), ("baixo", "Baixo")],
                        default="medio",
                        max_length=10,
                    ),
                ),
                ("valor_causa", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("prazo_proximo", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical processo",
                "verbose_name_plural": "historical processos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Processo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("trabalhista", "Trabalhista"),
                            ("civel", "Cível"),
                            ("criminal", "Criminal"),
                            ("tributario", "Tributário"),
                            ("contratual", "Contratual"),
                            ("regulatorio", "Regulatório"),
                            ("outro", "Outro"),
                        ],
                        default="civel",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("em_andamento", "Em andamento"),
                            ("ganho", "Ganho"),
                            ("perdido", "Perdido"),
                            ("acordo", "Acordo"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="em_andamento",
                        max_length=20,
                    ),
                ),
                ("parte", models.CharField(max_length=200)),
                ("advogado", models.CharField(blank=True, max_length=200)),
                ("foro", models.CharField(blank=True, max_length=100)),
                (
                    "risco",
                    models.CharField(
                        choices=[("alto", "Alto"), ("medio", "Médio"), ("baixo", "Baixo")],
                        default="medio",
                        max_length=10,
                    ),
                ),
                ("valor_causa", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("prazo_proximo", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="juridico_pr_tenant__1514e8_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "prazo_proximo"], name="juridico_pr_tenant__897e63_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPrazo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("audiencia", "Audiência"),
                            ("peca_processual", "Peça processual"),
                            ("contrato", "Contrato"),
                            ("administrativo", "Administrativo"),
                            ("outro", "Outro"),
                        ],
                        default="administrativo",
                        max_length=20,
                    ),
                ),
                ("prazo", models.DateField()),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("concluido", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="juridico.contrato",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="juridico.processo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical prazo",
                "verbose_name_plural": "historical prazos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Prazo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("audiencia", "Audiência"),
                            ("peca_processual", "Peça processual"),
                            ("contrato", "Contrato"),
                            ("administrativo", "Administrativo"),
                            ("outro", "Outro"),
                        ],
                        default="administrativo",
                        max_length=20,
                    ),
                ),
                ("prazo", models.DateField()),
                (
                    "urgencia",
                    models.CharField(
                        choices=[
                            ("critica", "Crítica"),
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                ("descricao", models.TextField(blank=True)),
                ("concluido", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prazos",
                        to="juridico.contrato",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prazos",
                        to="juridico.processo",
                    ),
                ),
            ],
            options={
                "ordering": ["prazo"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "prazo"], name="juridico_pr_tenant__338e13_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "urgencia"], name="juridico_pr_tenant__77de56_idx"
                    ),
                ],
            },
        ),
    ]
