# Generated by Django 5.2.17 on 2026-09-25 20:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("juridico", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contrato",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="historicalprazo",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="prazo",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name="processo",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
