# Generated by Django 5.2.17 on 2026-09-26 15:40

import django.db.models.deletion
import django.utils.timezone
import juridico.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("erp", "0009_datas_de_emissao_sem_hora"),
        ("juridico", "0002_contrato_updated_at_historicalcontrato_updated_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeloDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("procuracao", "Procuração"),
                            ("peticao", "Petição"),
                            ("notificacao", "Notificação"),
                            ("parecer", "Parecer"),
                            ("ata", "Ata"),
                            ("termo", "Termo / declaração"),
                            ("outro", "Outro"),
                        ],
                        default="contrato",
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=300)),
                ("corpo", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="contrato",
            name="aviso_dias",
            field=models.PositiveIntegerField(
                default=30, help_text="Avisar quantos dias antes do fim."
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="indice_reajuste",
            field=models.CharField(blank=True, help_text="IPCA, IGP-M...", max_length=30),
        ),
        migrations.AddField(
            model_name="contrato",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contratos_juridicos",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="contrato",
            name="responsavel",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="aviso_dias",
            field=models.PositiveIntegerField(
                default=30, help_text="Avisar quantos dias antes do fim."
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="indice_reajuste",
            field=models.CharField(blank=True, help_text="IPCA, IGP-M...", max_length=30),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="parceiro",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontrato",
            name="responsavel",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalprazo",
            name="concluido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprazo",
            name="contagem",
            field=models.CharField(
                choices=[("uteis", "Dias úteis (CPC)"), ("corridos", "Dias corridos")],
                default="uteis",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalprazo",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprazo",
            name="dias",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="assunto",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="classe",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="data_distribuicao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="fase",
            field=models.CharField(
                choices=[
                    ("conhecimento", "Conhecimento"),
                    ("recursal", "Recursal"),
                    ("execucao", "Execução / cumprimento"),
                    ("encerrado", "Encerrado"),
                ],
                default="conhecimento",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="instancia",
            field=models.CharField(
                choices=[
                    ("1", "1ª instância"),
                    ("2", "2ª instância"),
                    ("superior", "Tribunal superior"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="numero_cnj",
            field=models.CharField(
                blank=True, db_index=True, help_text="NNNNNNN-DD.AAAA.J.TR.OOOO", max_length=25
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="orgao_julgador",
            field=models.CharField(blank=True, help_text="Vara / câmara / turma", max_length=200),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="parte_contraria",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="polo",
            field=models.CharField(
                choices=[
                    ("ativo", "Autor (polo ativo)"),
                    ("passivo", "Réu (polo passivo)"),
                    ("terceiro", "Terceiro"),
                ],
                default="passivo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="probabilidade_perda",
            field=models.CharField(
                choices=[("provavel", "Provável"), ("possivel", "Possível"), ("remota", "Remota")],
                default="possivel",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="sincronizacao_msg",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="tribunal",
            field=models.CharField(
                blank=True, help_text="Sigla DataJud, ex.: tjsp, trt2", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="ultima_sincronizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprocesso",
            name="valor_estimado_perda",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quanto a empresa pode pagar se perder (base da provisão).",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="prazo",
            name="concluido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prazo",
            name="contagem",
            field=models.CharField(
                choices=[("uteis", "Dias úteis (CPC)"), ("corridos", "Dias corridos")],
                default="uteis",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="prazo",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="prazo",
            name="dias",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processo",
            name="assunto",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="processo",
            name="classe",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="processo",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processos",
                to="erp.parceironegocio",
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="data_distribuicao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processo",
            name="fase",
            field=models.CharField(
                choices=[
                    ("conhecimento", "Conhecimento"),
                    ("recursal", "Recursal"),
                    ("execucao", "Execução / cumprimento"),
                    ("encerrado", "Encerrado"),
                ],
                default="conhecimento",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="instancia",
            field=models.CharField(
                choices=[
                    ("1", "1ª instância"),
                    ("2", "2ª instância"),
                    ("superior", "Tribunal superior"),
                ],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="numero_cnj",
            field=models.CharField(
                blank=True, db_index=True, help_text="NNNNNNN-DD.AAAA.J.TR.OOOO", max_length=25
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="orgao_julgador",
            field=models.CharField(blank=True, help_text="Vara / câmara / turma", max_length=200),
        ),
        migrations.AddField(
            model_name="processo",
            name="parte_contraria",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="processo",
            name="polo",
            field=models.CharField(
                choices=[
                    ("ativo", "Autor (polo ativo)"),
                    ("passivo", "Réu (polo passivo)"),
                    ("terceiro", "Terceiro"),
                ],
                default="passivo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="probabilidade_perda",
            field=models.CharField(
                choices=[("provavel", "Provável"), ("possivel", "Possível"), ("remota", "Remota")],
                default="possivel",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="sincronizacao_msg",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="processo",
            name="tribunal",
            field=models.CharField(
                blank=True, help_text="Sigla DataJud, ex.: tjsp, trt2", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="processo",
            name="ultima_sincronizacao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="processo",
            name="valor_estimado_perda",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Quanto a empresa pode pagar se perder (base da provisão).",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="contrato",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("em_revisao", "Em revisão"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("vigente", "Vigente"),
                    ("expirando", "Expirando"),
                    ("vencido", "Vencido"),
                    ("negociacao", "Em negociação"),
                    ("cancelado", "Cancelado"),
                ],
                default="vigente",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcontrato",
            name="status",
            field=models.CharField(
                choices=[
                    ("rascunho", "Rascunho"),
                    ("em_revisao", "Em revisão"),
                    ("aguardando_assinatura", "Aguardando assinatura"),
                    ("vigente", "Vigente"),
                    ("expirando", "Expirando"),
                    ("vencido", "Vencido"),
                    ("negociacao", "Em negociação"),
                    ("cancelado", "Cancelado"),
                ],
                default="vigente",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprocesso",
            name="foro",
            field=models.CharField(
                blank=True, help_text="Comarca / seção judiciária", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="historicalprocesso",
            name="parte",
            field=models.CharField(help_text="Parte representada (texto livre).", max_length=200),
        ),
        migrations.AlterField(
            model_name="historicalprocesso",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_andamento", "Em andamento"),
                    ("suspenso", "Suspenso"),
                    ("ganho", "Ganho"),
                    ("perdido", "Perdido"),
                    ("acordo", "Acordo"),
                    ("arquivado", "Arquivado"),
                ],
                default="em_andamento",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalprocesso",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("trabalhista", "Trabalhista"),
                    ("civel", "Cível"),
                    ("criminal", "Criminal"),
                    ("tributario", "Tributário"),
                    ("contratual", "Contratual"),
                    ("regulatorio", "Regulatório"),
                    ("consumidor", "Consumidor"),
                    ("administrativo", "Administrativo"),
                    ("outro", "Outro"),
                ],
                default="civel",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="foro",
            field=models.CharField(
                blank=True, help_text="Comarca / seção judiciária", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="parte",
            field=models.CharField(help_text="Parte representada (texto livre).", max_length=200),
        ),
        migrations.AlterField(
            model_name="processo",
            name="status",
            field=models.CharField(
                choices=[
                    ("em_andamento", "Em andamento"),
                    ("suspenso", "Suspenso"),
                    ("ganho", "Ganho"),
                    ("perdido", "Perdido"),
                    ("acordo", "Acordo"),
                    ("arquivado", "Arquivado"),
                ],
                default="em_andamento",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="processo",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("trabalhista", "Trabalhista"),
                    ("civel", "Cível"),
                    ("criminal", "Criminal"),
                    ("tributario", "Tributário"),
                    ("contratual", "Contratual"),
                    ("regulatorio", "Regulatório"),
                    ("consumidor", "Consumidor"),
                    ("administrativo", "Administrativo"),
                    ("outro", "Outro"),
                ],
                default="civel",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("procuracao", "Procuração"),
                            ("peticao", "Petição"),
                            ("notificacao", "Notificação"),
                            ("parecer", "Parecer"),
                            ("ata", "Ata"),
                            ("termo", "Termo / declaração"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("final", "Versão final"),
                            ("em_assinatura", "Em assinatura"),
                            ("assinado", "Assinado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField(blank=True)),
                ("arquivo", models.FileField(blank=True, upload_to=juridico.models._doc_path)),
                ("nome_arquivo", models.CharField(blank=True, max_length=255)),
                ("tamanho", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="juridico.contrato",
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="juridico.processo",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos",
                        to="juridico.modelodocumento",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalModeloDocumento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=200)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("procuracao", "Procuração"),
                            ("peticao", "Petição"),
                            ("notificacao", "Notificação"),
                            ("parecer", "Parecer"),
                            ("ata", "Ata"),
                            ("termo", "Termo / declaração"),
                            ("outro", "Outro"),
                        ],
                        default="contrato",
                        max_length=20,
                    ),
                ),
                ("descricao", models.CharField(blank=True, max_length=300)),
                ("corpo", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical modelo documento",
                "verbose_name_plural": "historical modelo documentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSolicitacaoAssinatura",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviada", "Enviada"),
                            ("concluida", "Concluída"),
                            ("recusada", "Recusada"),
                            ("cancelada", "Cancelada"),
                            ("expirada", "Expirada"),
                        ],
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("provedor", models.CharField(default="interno", max_length=20)),
                ("provedor_ref", models.CharField(blank=True, max_length=120)),
                ("exigir_codigo_email", models.BooleanField(default=True)),
                ("ordem_sequencial", models.BooleanField(default=False)),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                ("pdf_original", models.TextField(blank=True, max_length=100)),
                ("hash_original", models.CharField(blank=True, max_length=64)),
                ("arquivo_assinado", models.TextField(blank=True, max_length=100)),
                ("hash_assinado", models.CharField(blank=True, db_index=True, max_length=64)),
                ("enviada_em", models.DateTimeField(blank=True, null=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("criado_por", models.CharField(blank=True, max_length=150)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="juridico.documento",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical solicitacao assinatura",
                "verbose_name_plural": "historical solicitacao assinaturas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalDocumento",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("procuracao", "Procuração"),
                            ("peticao", "Petição"),
                            ("notificacao", "Notificação"),
                            ("parecer", "Parecer"),
                            ("ata", "Ata"),
                            ("termo", "Termo / declaração"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("final", "Versão final"),
                            ("em_assinatura", "Em assinatura"),
                            ("assinado", "Assinado"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("conteudo", models.TextField(blank=True)),
                ("arquivo", models.TextField(blank=True, max_length=100)),
                ("nome_arquivo", models.CharField(blank=True, max_length=255)),
                ("tamanho", models.PositiveIntegerField(default=0)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("versao", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="juridico.contrato",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "processo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="juridico.processo",
                    ),
                ),
                (
                    "modelo",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="juridico.modelodocumento",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical documento",
                "verbose_name_plural": "historical documentos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SolicitacaoAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("enviada", "Enviada"),
                            ("concluida", "Concluída"),
                            ("recusada", "Recusada"),
                            ("cancelada", "Cancelada"),
                            ("expirada", "Expirada"),
                        ],
                        default="rascunho",
                        max_length=12,
                    ),
                ),
                ("provedor", models.CharField(default="interno", max_length=20)),
                ("provedor_ref", models.CharField(blank=True, max_length=120)),
                ("exigir_codigo_email", models.BooleanField(default=True)),
                ("ordem_sequencial", models.BooleanField(default=False)),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                ("pdf_original", models.FileField(blank=True, upload_to=juridico.models._doc_path)),
                ("hash_original", models.CharField(blank=True, max_length=64)),
                (
                    "arquivo_assinado",
                    models.FileField(blank=True, upload_to=juridico.models._doc_path),
                ),
                ("hash_assinado", models.CharField(blank=True, db_index=True, max_length=64)),
                ("enviada_em", models.DateTimeField(blank=True, null=True)),
                ("concluida_em", models.DateTimeField(blank=True, null=True)),
                ("criado_por", models.CharField(blank=True, max_length=150)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assinaturas",
                        to="juridico.documento",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Signatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("cpf_encrypted", models.TextField(blank=True)),
                ("cpf_mascarado", models.CharField(blank=True, max_length=20)),
                (
                    "papel",
                    models.CharField(
                        choices=[
                            ("parte", "Parte"),
                            ("testemunha", "Testemunha"),
                            ("aprovador", "Aprovador"),
                            ("representante", "Representante legal"),
                        ],
                        default="parte",
                        max_length=15,
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=1)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("token_encrypted", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("visualizou", "Visualizou"),
                            ("assinou", "Assinou"),
                            ("recusou", "Recusou"),
                        ],
                        default="pendente",
                        max_length=12,
                    ),
                ),
                ("codigo_hash", models.CharField(blank=True, max_length=64)),
                ("codigo_expira_em", models.DateTimeField(blank=True, null=True)),
                ("codigo_tentativas", models.PositiveIntegerField(default=0)),
                ("codigo_verificado", models.BooleanField(default=False)),
                ("convite_enviado_em", models.DateTimeField(blank=True, null=True)),
                ("visualizado_em", models.DateTimeField(blank=True, null=True)),
                ("assinado_em", models.DateTimeField(blank=True, null=True)),
                ("nome_assinatura", models.CharField(blank=True, max_length=200)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("recusa_motivo", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatarios",
                        to="juridico.solicitacaoassinatura",
                    ),
                ),
            ],
            options={
                "ordering": ["ordem", "id"],
            },
        ),
        migrations.CreateModel(
            name="EventoAssinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("tipo", models.CharField(max_length=30)),
                ("detalhe", models.CharField(blank=True, max_length=500)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("hash_encadeado", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "signatario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos",
                        to="juridico.signatario",
                    ),
                ),
                (
                    "solicitacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos",
                        to="juridico.solicitacaoassinatura",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="Andamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("data", models.DateTimeField(default=django.utils.timezone.now)),
                ("descricao", models.TextField()),
                (
                    "origem",
                    models.CharField(
                        choices=[("manual", "Manual"), ("datajud", "DataJud (CNJ)")],
                        default="manual",
                        max_length=10,
                    ),
                ),
                ("chave", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "processo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="andamentos",
                        to="juridico.processo",
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("chave", ""), _negated=True),
                        fields=("processo", "chave"),
                        name="uniq_andamento_chave_por_processo",
                    )
                ],
            },
        ),
    ]
