# Generated by Django 5.2.17 on 2026-08-24 22:47

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSector',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110)),
                ('description', models.TextField(blank=True)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=0, help_text='Orçamento mensal do setor, em USD. 0 = sem limite definido.', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('knowledge_source', models.ForeignKey(blank=True, db_constraint=False, help_text="Base de conhecimento própria deste setor (o 'cérebro secundário').", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ingestion.knowledgesource')),
            ],
            options={
                'verbose_name': 'historical sector',
                'verbose_name_plural': 'historical sectors',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110)),
                ('description', models.TextField(blank=True)),
                ('monthly_budget_usd', models.DecimalField(decimal_places=2, default=0, help_text='Orçamento mensal do setor, em USD. 0 = sem limite definido.', max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('knowledge_source', models.ForeignKey(blank=True, help_text="Base de conhecimento própria deste setor (o 'cérebro secundário').", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_sectors', to='ingestion.knowledgesource')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAgent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="Ex: 'Orquestrador de Backend', 'CEO', 'Analista de Suporte'.", max_length=150)),
                ('access_level', models.CharField(choices=[('operational', 'Operacional (só o próprio setor)'), ('sector_orchestrator', 'Orquestrador de Setor (medeia o próprio setor)'), ('general_orchestrator', 'Orquestrador-Geral (acesso total, medeia entre setores)'), ('ceo', 'CEO (acesso total)')], default='operational', max_length=25)),
                ('work_status', models.CharField(choices=[('idle', 'Ocioso'), ('working', 'Trabalhando'), ('paused', 'Pausado')], default='idle', max_length=20)),
                ('current_task', models.CharField(blank=True, max_length=255)),
                ('backlog_tasks', models.JSONField(blank=True, default=list, help_text='Tarefas pausadas (ex: por intervenção de um orquestrador/CEO), preservadas para retomada.')),
                ('default_provider', models.CharField(blank=True, max_length=20)),
                ('default_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency.sector')),
            ],
            options={
                'verbose_name': 'historical agent',
                'verbose_name_plural': 'historical agents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text="Ex: 'Orquestrador de Backend', 'CEO', 'Analista de Suporte'.", max_length=150)),
                ('access_level', models.CharField(choices=[('operational', 'Operacional (só o próprio setor)'), ('sector_orchestrator', 'Orquestrador de Setor (medeia o próprio setor)'), ('general_orchestrator', 'Orquestrador-Geral (acesso total, medeia entre setores)'), ('ceo', 'CEO (acesso total)')], default='operational', max_length=25)),
                ('work_status', models.CharField(choices=[('idle', 'Ocioso'), ('working', 'Trabalhando'), ('paused', 'Pausado')], default='idle', max_length=20)),
                ('current_task', models.CharField(blank=True, max_length=255)),
                ('backlog_tasks', models.JSONField(blank=True, default=list, help_text='Tarefas pausadas (ex: por intervenção de um orquestrador/CEO), preservadas para retomada.')),
                ('default_provider', models.CharField(blank=True, max_length=20)),
                ('default_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agency.sector')),
            ],
            options={
                'ordering': ['sector', '-access_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('content', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Aguardando um orquestrador mediar'), ('answered', 'Respondida'), ('rejected', 'Rejeitada (sem orquestrador autorizado a mediar)')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('from_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='agency.agent')),
                ('relayed_by', models.ForeignKey(blank=True, help_text='Orquestrador (de setor ou geral) ou CEO que mediou esta mensagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relayed_messages', to='agency.agent')),
                ('to_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='agency.sector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('estimated_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('query_log_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='agency.agent')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'agent', 'created_at'], name='agency_agen_tenant__06439d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sector',
            index=models.Index(fields=['tenant_id', 'slug'], name='agency_sect_tenant__9ed998_idx'),
        ),
        migrations.AddConstraint(
            model_name='sector',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'slug'), name='uniq_sector_slug_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant_id', 'sector'], name='agency_agen_tenant__0d49c9_idx'),
        ),
        migrations.AddIndex(
            model_name='agent',
            index=models.Index(fields=['tenant_id', 'access_level'], name='agency_agen_tenant__ded5e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('access_level__in', ['general_orchestrator', 'ceo']), ('sector__isnull', True)), models.Q(('access_level__in', ['operational', 'sector_orchestrator']), ('sector__isnull', False)), _connector='OR'), name='agent_sector_matches_access_level'),
        ),
        migrations.AddIndex(
            model_name='sectormessage',
            index=models.Index(fields=['tenant_id', 'status'], name='agency_sect_tenant__9aa73e_idx'),
        ),
    ]
