# Generated by Django 5.2.17 on 2026-08-30 03:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_historicalproject_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='autonomy_level',
            field=models.IntegerField(choices=[(0, 'Observador (só monitora/consulta risco baixo)'), (1, 'Recomendador (analisa e sugere, nunca executa sozinho)'), (2, 'Executor Supervisionado (executa só com aprovação, exceto risco baixo)'), (3, 'Executor por Política (auto-executa dentro de regras liberadas, nunca crítico)'), (4, 'Autônomo (auto-executa até risco crítico, se a política liberar)')], default=0),
        ),
        migrations.AddField(
            model_name='historicalagent',
            name='autonomy_level',
            field=models.IntegerField(choices=[(0, 'Observador (só monitora/consulta risco baixo)'), (1, 'Recomendador (analisa e sugere, nunca executa sozinho)'), (2, 'Executor Supervisionado (executa só com aprovação, exceto risco baixo)'), (3, 'Executor por Política (auto-executa dentro de regras liberadas, nunca crítico)'), (4, 'Autônomo (auto-executa até risco crítico, se a política liberar)')], default=0),
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('function_name', models.CharField(max_length=100)),
                ('params', models.JSONField(default=dict)),
                ('risk', models.CharField(max_length=10)),
                ('reason', models.CharField(help_text='Por que a política exigiu aprovação.', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Aguardando decisão'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('result', models.JSONField(blank=True, help_text='Resultado da execução, preenchido só se aprovado.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='agency.agent')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'status'], name='agency_pend_tenant__d7eae1_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('risk', models.CharField(choices=[('medium', 'Médio'), ('high', 'Alto'), ('critical', 'Crítico')], max_length=10)),
                ('min_autonomy_level', models.IntegerField(choices=[(0, 'Observador (só monitora/consulta risco baixo)'), (1, 'Recomendador (analisa e sugere, nunca executa sozinho)'), (2, 'Executor Supervisionado (executa só com aprovação, exceto risco baixo)'), (3, 'Executor por Política (auto-executa dentro de regras liberadas, nunca crítico)'), (4, 'Autônomo (auto-executa até risco crítico, se a política liberar)')], default=3, help_text='Nível mínimo de autonomia do agente para esta regra liberar execução automática.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sector', models.ForeignKey(blank=True, help_text='Vazio = regra vale para o tenant inteiro.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='agency.sector')),
            ],
            options={
                'ordering': ['risk'],
                'indexes': [models.Index(fields=['tenant_id', 'risk', 'is_active'], name='agency_poli_tenant__0cafb2_idx')],
            },
        ),
    ]
