# Generated by Django 5.2.17 on 2026-09-16 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_historicaltask_result_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='workspace',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
