# Generated by Django 5.2.17 on 2026-09-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agency", "0006_historicaltask_workspace_task_workspace"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="origin",
            field=models.CharField(
                choices=[
                    ("created", "Criado (template novo)"),
                    ("imported", "Importado (repositório já existia)"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="origin",
            field=models.CharField(
                choices=[
                    ("created", "Criado (template novo)"),
                    ("imported", "Importado (repositório já existia)"),
                ],
                default="created",
                max_length=20,
            ),
        ),
    ]
