# Generated by Django 5.2.17 on 2026-09-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0007_project_local_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="agent",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="System prompt deste agente (persona, regras, formato de saída). Injetado em toda chamada de IA.",
            ),
        ),
        migrations.AddField(
            model_name="historicalagent",
            name="instructions",
            field=models.TextField(
                blank=True,
                help_text="System prompt deste agente (persona, regras, formato de saída). Injetado em toda chamada de IA.",
            ),
        ),
    ]
