# Generated by Django 5.2.17 on 2026-09-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0009_agent_updated_at_historicalagent_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsector",
            name="default_model",
            field=models.CharField(
                blank=True,
                help_text="Modelo fixo do setor. Vazio = default_model da credencial do provedor.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="historicalsector",
            name="default_provider",
            field=models.CharField(
                blank=True,
                help_text="Provedor de IA fixo do setor (ex: 'anthropic'). Vazio = padrão do tenant.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="default_model",
            field=models.CharField(
                blank=True,
                help_text="Modelo fixo do setor. Vazio = default_model da credencial do provedor.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="sector",
            name="default_provider",
            field=models.CharField(
                blank=True,
                help_text="Provedor de IA fixo do setor (ex: 'anthropic'). Vazio = padrão do tenant.",
                max_length=20,
            ),
        ),
    ]
