# Generated by Django 5.2.17 on 2026-09-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0011_desenvolvimento_usa_claude"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinteraction",
            name="source_document_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
