# Generated by Django 5.2.17 on 2026-09-26 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0012_interaction_source_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinteraction",
            name="model",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="agentinteraction",
            name="provider",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="agentinteraction",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interactions",
                to="agency.task",
            ),
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="runs_externally",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sectormessage",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="runs_externally",
            field=models.BooleanField(default=False),
        ),
    ]
