# Generated by Django 5.2.17 on 2026-09-26 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0013_ai_cost_timeline"),
    ]

    operations = [
        migrations.AddField(
            model_name="agentinteraction",
            name="tokens_estimated",
            field=models.BooleanField(default=True),
        ),
    ]
