# Generated by Django 5.2.17 on 2026-09-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0014_tokens_estimated"),
        ("ingestion", "0005_conectores_segredos_sync"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="extra_knowledge_sources",
            field=models.ManyToManyField(
                blank=True,
                help_text="Fontes adicionais que os agentes deste setor podem consultar.",
                related_name="agency_sectors_extra",
                to="ingestion.knowledgesource",
            ),
        ),
    ]
