# Generated by Django 5.2.17 on 2026-08-30 19:50

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_agent_autonomy_level_historicalagent_autonomy_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalTask',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('brief', models.TextField(help_text='O que a tarefa pede — o prompt original do agente.')),
                ('status', models.CharField(choices=[('created', 'Criada'), ('in_progress', 'Em andamento'), ('paused_ceo', 'Pausada pelo CEO'), ('adapted', 'Adaptada (nova instrução, retomando)'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='created', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='0.0 a 1.0 — só informativo, não trava nada.')),
                ('current_files', models.JSONField(blank=True, default=list, help_text='Paths dos arquivos que a tarefa produziu até agora.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('task_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('agent', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency.agent')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='agency.project')),
            ],
            options={
                'verbose_name': 'historical task',
                'verbose_name_plural': 'historical tasks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('brief', models.TextField(help_text='O que a tarefa pede — o prompt original do agente.')),
                ('status', models.CharField(choices=[('created', 'Criada'), ('in_progress', 'Em andamento'), ('paused_ceo', 'Pausada pelo CEO'), ('adapted', 'Adaptada (nova instrução, retomando)'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], default='created', max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='0.0 a 1.0 — só informativo, não trava nada.')),
                ('current_files', models.JSONField(blank=True, default=list, help_text='Paths dos arquivos que a tarefa produziu até agora.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('task_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='agency.agent')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='agency.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('context', models.JSONField(help_text='brief/progress/current_files/status no momento da interrupção.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='agency.task')),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['tenant_id', 'agent', 'status'], name='agency_task_tenant__51d48b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasksnapshot',
            unique_together={('task', 'version')},
        ),
    ]
