# Generated by Django 5.2.17 on 2026-08-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_historicaltask_task_tasksnapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='result',
            field=models.JSONField(blank=True, default=dict, help_text="Saída estruturada da execução (plan/steps/output/needs_review) ou {'error': ...}."),
        ),
        migrations.AddField(
            model_name='task',
            name='result',
            field=models.JSONField(blank=True, default=dict, help_text="Saída estruturada da execução (plan/steps/output/needs_review) ou {'error': ...}."),
        ),
    ]
