# Generated by Django 5.2.17 on 2026-08-24 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.UUIDField(blank=True, db_index=True, editable=False, null=True)),
                ('question', models.TextField()),
                ('model_category', models.CharField(blank=True, max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('function_called', models.CharField(blank=True, max_length=150)),
                ('function_params', models.JSONField(blank=True, default=dict)),
                ('function_result', models.JSONField(blank=True, default=dict)),
                ('answer', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ok', 'Sucesso'), ('function_error', 'Erro ao executar função'), ('llm_error', 'Erro no modelo de IA'), ('rejected', 'Função não encontrada/negada')], default='ok', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='orchestrati_tenant__588a3e_idx')],
            },
        ),
    ]
