# Generated by Django 5.2.17 on 2026-09-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orchestration", "0002_alter_querylog_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="cost_estimated_usd",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="querylog",
            name="tokens_completion",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="querylog",
            name="tokens_prompt",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
