# Generated by Django 5.2.17 on 2026-08-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='status',
            field=models.CharField(choices=[('ok', 'Sucesso'), ('function_error', 'Erro ao executar função'), ('llm_error', 'Erro no modelo de IA'), ('rejected', 'Função não encontrada/negada'), ('pending_approval', 'Aguardando aprovação humana (policy engine)')], default='ok', max_length=20),
        ),
    ]
