# Generated by Django 5.2.17 on 2026-09-25 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compras", "0002_remove_fornecedor_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fornecedor",
            name="nota_media",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="pedidos_no_prazo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="prazo_medio_dias",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fornecedor",
            name="total_pedidos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalfornecedor",
            name="nota_media",
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=4),
        ),
        migrations.AddField(
            model_name="historicalfornecedor",
            name="pedidos_no_prazo",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalfornecedor",
            name="prazo_medio_dias",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfornecedor",
            name="total_pedidos",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalorcamento",
            name="recomendacao_motivo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalorcamento",
            name="score_recomendacao",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="historicalpedidocompra",
            name="confirmado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalpedidocompra",
            name="em_transito_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="recomendacao_motivo",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orcamento",
            name="score_recomendacao",
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="pedidocompra",
            name="confirmado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pedidocompra",
            name="em_transito_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
