# Generated by Django 5.2.17 on 2026-09-23 21:40

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPipeline",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("running", "Executando"),
                            ("failed", "Falhou"),
                            ("pending", "Pendente"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("branch", models.CharField(max_length=200)),
                ("duracao", models.CharField(blank=True, max_length=20)),
                ("commit_sha", models.CharField(blank=True, max_length=40)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("executado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pipeline",
                "verbose_name_plural": "historical pipelines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPullRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("review", "Em revisão"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("revisoes", models.PositiveIntegerField(default=0)),
                ("conflitos", models.BooleanField(default=False)),
                ("data_criacao", models.DateField(default=django.utils.timezone.now)),
                ("merged_em", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical pull request",
                "verbose_name_plural": "historical pull requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSprint",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("numero", models.PositiveIntegerField(default=1)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("ativo", "Ativo"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejado",
                        max_length=15,
                    ),
                ),
                ("velocidade_planejada", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sprint",
                "verbose_name_plural": "historical sprints",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Pipeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("running", "Executando"),
                            ("failed", "Falhou"),
                            ("pending", "Pendente"),
                            ("cancelled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("branch", models.CharField(max_length=200)),
                ("duracao", models.CharField(blank=True, max_length=20)),
                ("commit_sha", models.CharField(blank=True, max_length=40)),
                ("autor", models.CharField(blank=True, max_length=200)),
                ("executado_em", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-executado_em"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="desenvolvim_tenant__b2fa48_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "branch"], name="desenvolvim_tenant__496568_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("numero", models.PositiveIntegerField()),
                ("titulo", models.CharField(max_length=255)),
                ("autor", models.CharField(max_length=200)),
                ("branch", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("review", "Em revisão"),
                            ("merged", "Merged"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("revisoes", models.PositiveIntegerField(default=0)),
                ("conflitos", models.BooleanField(default=False)),
                ("data_criacao", models.DateField(default=django.utils.timezone.now)),
                ("merged_em", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-numero"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="desenvolvim_tenant__b1d19f_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "numero"), name="uniq_pr_numero_per_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Sprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("nome", models.CharField(max_length=100)),
                ("numero", models.PositiveIntegerField(default=1)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejado", "Planejado"),
                            ("ativo", "Ativo"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejado",
                        max_length=15,
                    ),
                ),
                ("velocidade_planejada", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["-numero"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="desenvolvim_tenant__30d99d_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalSprintTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("feature", "Feature"), ("bug", "Bug"), ("chore", "Chore")],
                        default="feature",
                        max_length=10,
                    ),
                ),
                ("pontos", models.PositiveIntegerField(default=1)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("em_dev", "Em Dev"),
                            ("review", "Review"),
                            ("done", "Done"),
                        ],
                        default="backlog",
                        max_length=10,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[("alta", "Alta"), ("media", "Média"), ("baixa", "Baixa")],
                        default="media",
                        max_length=6,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sprint",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="desenvolvimento.sprint",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical sprint task",
                "verbose_name_plural": "historical sprint tasks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="SprintTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("feature", "Feature"), ("bug", "Bug"), ("chore", "Chore")],
                        default="feature",
                        max_length=10,
                    ),
                ),
                ("pontos", models.PositiveIntegerField(default=1)),
                ("responsavel", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("backlog", "Backlog"),
                            ("em_dev", "Em Dev"),
                            ("review", "Review"),
                            ("done", "Done"),
                        ],
                        default="backlog",
                        max_length=10,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[("alta", "Alta"), ("media", "Média"), ("baixa", "Baixa")],
                        default="media",
                        max_length=6,
                    ),
                ),
                ("descricao", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "sprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="desenvolvimento.sprint",
                    ),
                ),
            ],
            options={
                "ordering": ["sprint", "prioridade", "-pontos"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "sprint", "status"],
                        name="desenvolvim_tenant__0b75b8_idx",
                    )
                ],
            },
        ),
    ]
