# Generated by Django 5.2.17 on 2026-09-26 16:42

import django.db.models.deletion
import django.utils.timezone
import marketing.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("agency", "0015_conectores_segredos_sync"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContaSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "rede",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("discord", "Discord"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("usuario", models.CharField(blank=True, max_length=255)),
                (
                    "conta_id",
                    models.CharField(help_text="Id da conta/página/canal na rede.", max_length=255),
                ),
                ("url", models.URLField(blank=True)),
                ("_token", models.TextField(blank=True, db_column="token_encrypted")),
                ("_refresh", models.TextField(blank=True, db_column="refresh_encrypted")),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                ("escopos", models.CharField(blank=True, max_length=500)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("conectada", "Conectada"),
                            ("erro", "Com erro"),
                            ("expirada", "Token expirado"),
                        ],
                        default="conectada",
                        max_length=20,
                    ),
                ),
                ("mensagem", models.CharField(blank=True, max_length=500)),
                ("ultimo_teste", models.DateTimeField(blank=True, null=True)),
                ("conectada_por", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "ordering": ["rede", "nome"],
            },
        ),
        migrations.CreateModel(
            name="OAuthPendente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("state", models.CharField(max_length=64, unique=True)),
                (
                    "provedor",
                    models.CharField(
                        choices=[
                            ("meta", "Meta (Instagram + Facebook)"),
                            ("google", "Google (YouTube)"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("verificador", models.CharField(blank=True, max_length=128)),
                ("redirect_uri", models.URLField()),
                ("usuario", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AplicativoRede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "provedor",
                    models.CharField(
                        choices=[
                            ("meta", "Meta (Instagram + Facebook)"),
                            ("google", "Google (YouTube)"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                (
                    "_client_secret",
                    models.TextField(blank=True, db_column="client_secret_encrypted"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "provedor"), name="aplicativo_rede_unico_por_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAplicativoRede",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "provedor",
                    models.CharField(
                        choices=[
                            ("meta", "Meta (Instagram + Facebook)"),
                            ("google", "Google (YouTube)"),
                            ("tiktok", "TikTok"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client_id", models.CharField(max_length=255)),
                (
                    "_client_secret",
                    models.TextField(blank=True, db_column="client_secret_encrypted"),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical aplicativo rede",
                "verbose_name_plural": "historical aplicativo redes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalContaSocial",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "rede",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("x", "X (Twitter)"),
                            ("discord", "Discord"),
                            ("twitch", "Twitch"),
                        ],
                        max_length=20,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("usuario", models.CharField(blank=True, max_length=255)),
                (
                    "conta_id",
                    models.CharField(help_text="Id da conta/página/canal na rede.", max_length=255),
                ),
                ("url", models.URLField(blank=True)),
                ("_token", models.TextField(blank=True, db_column="token_encrypted")),
                ("_refresh", models.TextField(blank=True, db_column="refresh_encrypted")),
                ("expira_em", models.DateTimeField(blank=True, null=True)),
                ("escopos", models.CharField(blank=True, max_length=500)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("conectada", "Conectada"),
                            ("erro", "Com erro"),
                            ("expirada", "Token expirado"),
                        ],
                        default="conectada",
                        max_length=20,
                    ),
                ),
                ("mensagem", models.CharField(blank=True, max_length=500)),
                ("ultimo_teste", models.DateTimeField(blank=True, null=True)),
                ("conectada_por", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical conta social",
                "verbose_name_plural": "historical conta socials",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPerfilMarca",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("nome", models.CharField(blank=True, max_length=120)),
                ("ramo", models.CharField(blank=True, max_length=60)),
                (
                    "descricao",
                    models.TextField(blank=True, help_text="O que a empresa faz, em 2-3 frases."),
                ),
                ("publico_alvo", models.TextField(blank=True)),
                ("tom_de_voz", models.CharField(blank=True, max_length=255)),
                ("pilares", models.JSONField(blank=True, default=list)),
                ("diferenciais", models.TextField(blank=True)),
                (
                    "evitar",
                    models.TextField(
                        blank=True, help_text="Palavras, promessas e assuntos proibidos."
                    ),
                ),
                ("hashtags", models.CharField(blank=True, max_length=500)),
                ("cta_padrao", models.CharField(blank=True, max_length=255)),
                ("site", models.URLField(blank=True)),
                ("idioma", models.CharField(default="pt-BR", max_length=10)),
                ("cor_primaria", models.CharField(default="#10b981", max_length=7)),
                ("cor_secundaria", models.CharField(default="#161412", max_length=7)),
                ("cor_texto", models.CharField(default="#ffffff", max_length=7)),
                ("logo", models.TextField(blank=True, max_length=100)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical perfil marca",
                "verbose_name_plural": "historical perfil marcas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPublicacao",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("texto", models.TextField(blank=True)),
                ("pilar", models.CharField(blank=True, max_length=100)),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("carrossel", "Carrossel"),
                            ("reels", "Reels / Short / TikTok"),
                            ("video", "Vídeo"),
                            ("story", "Story"),
                            ("texto", "Só texto"),
                        ],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("gancho", models.CharField(blank=True, max_length=500)),
                ("hashtags", models.CharField(blank=True, max_length=500)),
                ("link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("revisao", "Aguardando aprovação"),
                            ("agendada", "Agendada"),
                            ("publicando", "Publicando"),
                            ("publicada", "Publicada"),
                            ("parcial", "Publicada em parte"),
                            ("erro", "Falhou"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("agendada_para", models.DateTimeField(blank=True, null=True)),
                ("escrita_por_ia", models.BooleanField(default=False)),
                ("fontes", models.JSONField(blank=True, default=list)),
                ("ideia_visual", models.TextField(blank=True)),
                ("aprovada_por", models.CharField(blank=True, max_length=255)),
                ("aprovada_em", models.DateTimeField(blank=True, null=True)),
                ("publicada_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="agency.agent",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical publicacao",
                "verbose_name_plural": "historical publicacaos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JobVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("cortes", "Cortes de vídeo"), ("video_ia", "Vídeo curto com IA")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("na_fila", "Na fila"),
                            ("baixando", "Baixando"),
                            ("transcrevendo", "Transcrevendo"),
                            ("analisando", "Escolhendo os melhores trechos"),
                            ("cortando", "Cortando"),
                            ("gerando", "Gerando vídeo"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="na_fila",
                        max_length=20,
                    ),
                ),
                ("progresso", models.PositiveSmallIntegerField(default=0)),
                ("etapa", models.CharField(blank=True, max_length=255)),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("origem_url", models.URLField(blank=True)),
                ("direitos_confirmados", models.BooleanField(default=False)),
                ("parametros", models.JSONField(blank=True, default=dict)),
                ("transcricao", models.JSONField(blank=True, default=list)),
                ("resultado", models.JSONField(blank=True, default=dict)),
                ("externo_id", models.CharField(blank=True, max_length=100)),
                ("erro", models.TextField(blank=True)),
                ("criado_por", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agency.agent",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalMidia",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagem", "Imagem"), ("video", "Vídeo")], max_length=10
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("upload", "Enviada"),
                            ("criativo", "Criativo gerado"),
                            ("corte", "Corte de vídeo"),
                            ("video_ia", "Vídeo IA (MoneyPrinterTurbo)"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("arquivo", models.TextField(max_length=100)),
                ("miniatura", models.TextField(blank=True, max_length=100)),
                ("formato", models.CharField(blank=True, max_length=30)),
                ("largura", models.PositiveIntegerField(default=0)),
                ("altura", models.PositiveIntegerField(default=0)),
                ("duracao", models.FloatField(default=0)),
                ("tamanho", models.PositiveBigIntegerField(default=0)),
                ("mime", models.CharField(blank=True, max_length=60)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("legenda_sugerida", models.TextField(blank=True)),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="marketing.jobvideo",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical midia",
                "verbose_name_plural": "historical midias",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Midia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("imagem", "Imagem"), ("video", "Vídeo")], max_length=10
                    ),
                ),
                (
                    "origem",
                    models.CharField(
                        choices=[
                            ("upload", "Enviada"),
                            ("criativo", "Criativo gerado"),
                            ("corte", "Corte de vídeo"),
                            ("video_ia", "Vídeo IA (MoneyPrinterTurbo)"),
                        ],
                        default="upload",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("arquivo", models.FileField(upload_to=marketing.models._arquivo)),
                ("miniatura", models.FileField(blank=True, upload_to=marketing.models._arquivo)),
                ("formato", models.CharField(blank=True, max_length=30)),
                ("largura", models.PositiveIntegerField(default=0)),
                ("altura", models.PositiveIntegerField(default=0)),
                ("duracao", models.FloatField(default=0)),
                ("tamanho", models.PositiveBigIntegerField(default=0)),
                ("mime", models.CharField(blank=True, max_length=60)),
                ("sha256", models.CharField(blank=True, max_length=64)),
                ("legenda_sugerida", models.TextField(blank=True)),
                ("dados", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="midias",
                        to="marketing.jobvideo",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="jobvideo",
            name="origem_midia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="marketing.midia",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalJobVideo",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("cortes", "Cortes de vídeo"), ("video_ia", "Vídeo curto com IA")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("na_fila", "Na fila"),
                            ("baixando", "Baixando"),
                            ("transcrevendo", "Transcrevendo"),
                            ("analisando", "Escolhendo os melhores trechos"),
                            ("cortando", "Cortando"),
                            ("gerando", "Gerando vídeo"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="na_fila",
                        max_length=20,
                    ),
                ),
                ("progresso", models.PositiveSmallIntegerField(default=0)),
                ("etapa", models.CharField(blank=True, max_length=255)),
                ("titulo", models.CharField(blank=True, max_length=255)),
                ("origem_url", models.URLField(blank=True)),
                ("direitos_confirmados", models.BooleanField(default=False)),
                ("parametros", models.JSONField(blank=True, default=dict)),
                ("transcricao", models.JSONField(blank=True, default=list)),
                ("resultado", models.JSONField(blank=True, default=dict)),
                ("externo_id", models.CharField(blank=True, max_length=100)),
                ("erro", models.TextField(blank=True)),
                ("criado_por", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="agency.agent",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origem_midia",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="marketing.midia",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical job video",
                "verbose_name_plural": "historical job videos",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PerfilMarca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("nome", models.CharField(blank=True, max_length=120)),
                ("ramo", models.CharField(blank=True, max_length=60)),
                (
                    "descricao",
                    models.TextField(blank=True, help_text="O que a empresa faz, em 2-3 frases."),
                ),
                ("publico_alvo", models.TextField(blank=True)),
                ("tom_de_voz", models.CharField(blank=True, max_length=255)),
                ("pilares", models.JSONField(blank=True, default=list)),
                ("diferenciais", models.TextField(blank=True)),
                (
                    "evitar",
                    models.TextField(
                        blank=True, help_text="Palavras, promessas e assuntos proibidos."
                    ),
                ),
                ("hashtags", models.CharField(blank=True, max_length=500)),
                ("cta_padrao", models.CharField(blank=True, max_length=255)),
                ("site", models.URLField(blank=True)),
                ("idioma", models.CharField(default="pt-BR", max_length=10)),
                ("cor_primaria", models.CharField(default="#10b981", max_length=7)),
                ("cor_secundaria", models.CharField(default="#161412", max_length=7)),
                ("cor_texto", models.CharField(default="#ffffff", max_length=7)),
                ("logo", models.FileField(blank=True, upload_to=marketing.models._arquivo)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id",), name="perfil_marca_unico_por_tenant"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Publicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("titulo", models.CharField(max_length=255)),
                ("texto", models.TextField(blank=True)),
                ("pilar", models.CharField(blank=True, max_length=100)),
                (
                    "formato",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("carrossel", "Carrossel"),
                            ("reels", "Reels / Short / TikTok"),
                            ("video", "Vídeo"),
                            ("story", "Story"),
                            ("texto", "Só texto"),
                        ],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("gancho", models.CharField(blank=True, max_length=500)),
                ("hashtags", models.CharField(blank=True, max_length=500)),
                ("link", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("revisao", "Aguardando aprovação"),
                            ("agendada", "Agendada"),
                            ("publicando", "Publicando"),
                            ("publicada", "Publicada"),
                            ("parcial", "Publicada em parte"),
                            ("erro", "Falhou"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                ("agendada_para", models.DateTimeField(blank=True, null=True)),
                ("escrita_por_ia", models.BooleanField(default=False)),
                ("fontes", models.JSONField(blank=True, default=list)),
                ("ideia_visual", models.TextField(blank=True)),
                ("aprovada_por", models.CharField(blank=True, max_length=255)),
                ("aprovada_em", models.DateTimeField(blank=True, null=True)),
                ("publicada_em", models.DateTimeField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="agency.agent",
                    ),
                ),
                (
                    "midias",
                    models.ManyToManyField(
                        blank=True, related_name="publicacoes", to="marketing.midia"
                    ),
                ),
            ],
            options={
                "ordering": ["agendada_para", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Destino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                (
                    "texto",
                    models.TextField(blank=True, help_text="Vazio = usa o texto da publicação."),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("publicando", "Publicando"),
                            ("publicado", "Publicado"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                ("externo_id", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("erro", models.TextField(blank=True)),
                ("tentativas", models.PositiveSmallIntegerField(default=0)),
                ("publicado_em", models.DateTimeField(blank=True, null=True)),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos",
                        to="marketing.contasocial",
                    ),
                ),
                (
                    "publicacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destinos",
                        to="marketing.publicacao",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("publicacao", "conta"), name="destino_unico_por_conta"
                    )
                ],
            },
        ),
    ]
