# Generated by Django 5.2.17 on 2026-09-25 02:03

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalScrapingJob",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("google_maps", "Google Maps"),
                            ("url", "URL (extração inteligente)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando"),
                            ("running", "Executando"),
                            ("done", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        blank=True, help_text="Busca Google Maps ou URL a extrair", max_length=500
                    ),
                ),
                ("lat", models.CharField(blank=True, max_length=30)),
                ("lng", models.CharField(blank=True, max_length=30)),
                (
                    "depth",
                    models.IntegerField(default=5, help_text="Profundidade de busca (Google Maps)"),
                ),
                (
                    "extraction_schema",
                    models.JSONField(
                        blank=True,
                        help_text="Schema desejado para extração de URL (ex: {'nome': str, 'preco': str})",
                        null=True,
                    ),
                ),
                ("results", models.JSONField(default=list)),
                ("result_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True, help_text="ID do job no gmaps-scraper", max_length=100
                    ),
                ),
                ("imported_to_crm", models.BooleanField(default=False)),
                ("imported_count", models.IntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical scraping job",
                "verbose_name_plural": "historical scraping jobs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ScrapingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tenant_id",
                    models.UUIDField(blank=True, db_index=True, editable=False, null=True),
                ),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("google_maps", "Google Maps"),
                            ("url", "URL (extração inteligente)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Aguardando"),
                            ("running", "Executando"),
                            ("done", "Concluído"),
                            ("failed", "Falhou"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "query",
                    models.CharField(
                        blank=True, help_text="Busca Google Maps ou URL a extrair", max_length=500
                    ),
                ),
                ("lat", models.CharField(blank=True, max_length=30)),
                ("lng", models.CharField(blank=True, max_length=30)),
                (
                    "depth",
                    models.IntegerField(default=5, help_text="Profundidade de busca (Google Maps)"),
                ),
                (
                    "extraction_schema",
                    models.JSONField(
                        blank=True,
                        help_text="Schema desejado para extração de URL (ex: {'nome': str, 'preco': str})",
                        null=True,
                    ),
                ),
                ("results", models.JSONField(default=list)),
                ("result_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_job_id",
                    models.CharField(
                        blank=True, help_text="ID do job no gmaps-scraper", max_length=100
                    ),
                ),
                ("imported_to_crm", models.BooleanField(default=False)),
                ("imported_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "status"], name="scraping_sc_tenant__38f184_idx"
                    ),
                    models.Index(
                        fields=["tenant_id", "job_type"], name="scraping_sc_tenant__f0c3df_idx"
                    ),
                ],
            },
        ),
    ]
